<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/websecurityscanner/v1alpha/scan_run.proto

namespace Google\Cloud\Websecurityscanner\V1alpha\ScanRun;

/**
 * Types of ScanRun execution state.
 *
 * Protobuf type <code>google.cloud.websecurityscanner.v1alpha.ScanRun.ExecutionState</code>
 */
class ExecutionState
{
    /**
     * Represents an invalid state caused by internal server error. This value
     * should never be returned.
     *
     * Generated from protobuf enum <code>EXECUTION_STATE_UNSPECIFIED = 0;</code>
     */
    const EXECUTION_STATE_UNSPECIFIED = 0;
    /**
     * The scan is waiting in the queue.
     *
     * Generated from protobuf enum <code>QUEUED = 1;</code>
     */
    const QUEUED = 1;
    /**
     * The scan is in progress.
     *
     * Generated from protobuf enum <code>SCANNING = 2;</code>
     */
    const SCANNING = 2;
    /**
     * The scan is either finished or stopped by user.
     *
     * Generated from protobuf enum <code>FINISHED = 3;</code>
     */
    const FINISHED = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ExecutionState::class, \Google\Cloud\Websecurityscanner\V1alpha\ScanRun_ExecutionState::class);

