<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/bigquery/logging/v1/audit_data.proto

namespace Google\Cloud\Bigquery\Logging\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Bigquery\Logging\V1\JobConfiguration\Extract instead.
     * @deprecated
     */
    class JobConfiguration_Extract {}
}
class_exists(JobConfiguration\Extract::class);
@trigger_error('Google\Cloud\Bigquery\Logging\V1\JobConfiguration_Extract is deprecated and will be removed in the next major release. Use Google\Cloud\Bigquery\Logging\V1\JobConfiguration\Extract instead', E_USER_DEPRECATED);

