<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/bigquery/logging/v1/audit_data.proto

namespace Google\Cloud\Bigquery\Logging\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes an external data source used in a query.
 *
 * Generated from protobuf message <code>google.cloud.bigquery.logging.v1.TableDefinition</code>
 */
class TableDefinition extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the table, used in queries.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Google Cloud Storage URIs for the data to be imported.
     *
     * Generated from protobuf field <code>repeated string source_uris = 2;</code>
     */
    private $source_uris;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Name of the table, used in queries.
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $source_uris
     *           Google Cloud Storage URIs for the data to be imported.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Bigquery\Logging\V1\AuditData::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the table, used in queries.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of the table, used in queries.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Google Cloud Storage URIs for the data to be imported.
     *
     * Generated from protobuf field <code>repeated string source_uris = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSourceUris()
    {
        return $this->source_uris;
    }

    /**
     * Google Cloud Storage URIs for the data to be imported.
     *
     * Generated from protobuf field <code>repeated string source_uris = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSourceUris($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->source_uris = $arr;

        return $this;
    }

}

