<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/language/v1beta1/language_service.proto

namespace Google\Cloud\Language\V1beta1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Language\V1beta1\PartOfSpeech\Reciprocity instead.
     * @deprecated
     */
    class PartOfSpeech_Reciprocity {}
}
class_exists(PartOfSpeech\Reciprocity::class);
@trigger_error('Google\Cloud\Language\V1beta1\PartOfSpeech_Reciprocity is deprecated and will be removed in the next major release. Use Google\Cloud\Language\V1beta1\PartOfSpeech\Reciprocity instead', E_USER_DEPRECATED);

