<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dialogflow/v2beta1/intent.proto

namespace Google\Cloud\Dialogflow\V2beta1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Dialogflow\V2beta1\Intent\Message\SelectItemInfo instead.
     * @deprecated
     */
    class Intent_Message_SelectItemInfo {}
}
class_exists(Intent\Message\SelectItemInfo::class);
@trigger_error('Google\Cloud\Dialogflow\V2beta1\Intent_Message_SelectItemInfo is deprecated and will be removed in the next major release. Use Google\Cloud\Dialogflow\V2beta1\Intent\Message\SelectItemInfo instead', E_USER_DEPRECATED);

