<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/servicemanagement/v1/resources.proto

namespace Google\Api\Servicemanagement\V1;

/**
 * Status of a Rollout.
 *
 * Protobuf enum <code>Google\Api\Servicemanagement\V1\Rollout\RolloutStatus</code>
 */
class Rollout_RolloutStatus
{
    /**
     * No status specified.
     *
     * Generated from protobuf enum <code>ROLLOUT_STATUS_UNSPECIFIED = 0;</code>
     */
    const ROLLOUT_STATUS_UNSPECIFIED = 0;
    /**
     * The Rollout is in progress.
     *
     * Generated from protobuf enum <code>IN_PROGRESS = 1;</code>
     */
    const IN_PROGRESS = 1;
    /**
     * The Rollout has completed successfully.
     *
     * Generated from protobuf enum <code>SUCCESS = 2;</code>
     */
    const SUCCESS = 2;
    /**
     * The Rollout has been cancelled. This can happen if you have overlapping
     * Rollout pushes, and the previous ones will be cancelled.
     *
     * Generated from protobuf enum <code>CANCELLED = 3;</code>
     */
    const CANCELLED = 3;
    /**
     * The Rollout has failed. It is typically caused by configuration errors.
     *
     * Generated from protobuf enum <code>FAILED = 4;</code>
     */
    const FAILED = 4;
    /**
     * The Rollout has not started yet and is pending for execution.
     *
     * Generated from protobuf enum <code>PENDING = 5;</code>
     */
    const PENDING = 5;
}

