<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/admin/v1/iam.proto

namespace Google\Iam\Admin\V1;

/**
 * Supported key algorithms.
 *
 * Protobuf type <code>google.iam.admin.v1.ServiceAccountKeyAlgorithm</code>
 */
class ServiceAccountKeyAlgorithm
{
    /**
     * An unspecified key algorithm.
     *
     * Generated from protobuf enum <code>KEY_ALG_UNSPECIFIED = 0;</code>
     */
    const KEY_ALG_UNSPECIFIED = 0;
    /**
     * 1k RSA Key.
     *
     * Generated from protobuf enum <code>KEY_ALG_RSA_1024 = 1;</code>
     */
    const KEY_ALG_RSA_1024 = 1;
    /**
     * 2k RSA Key.
     *
     * Generated from protobuf enum <code>KEY_ALG_RSA_2048 = 2;</code>
     */
    const KEY_ALG_RSA_2048 = 2;
}

