<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/support/common.proto

namespace Google\Cloud\Support\Common\SupportRole;

/**
 * A role which determines the support resources and features a user might
 * get access to.
 *
 * Protobuf type <code>google.cloud.support.common.SupportRole.Role</code>
 */
class Role
{
    /**
     * An unknown role.
     *
     * Generated from protobuf enum <code>ROLE_UNSPECIFIED = 0;</code>
     */
    const ROLE_UNSPECIFIED = 0;
    /**
     * The basic support role.
     *
     * Generated from protobuf enum <code>BASIC = 1;</code>
     */
    const BASIC = 1;
    /**
     * The developer role.
     *
     * Generated from protobuf enum <code>DEVELOPER = 2;</code>
     */
    const DEVELOPER = 2;
    /**
     * The operation role.
     *
     * Generated from protobuf enum <code>OPERATION = 3;</code>
     */
    const OPERATION = 3;
    /**
     * The site reliability role.
     *
     * Generated from protobuf enum <code>SITE_RELIABILITY = 4;</code>
     */
    const SITE_RELIABILITY = 4;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Role::class, \Google\Cloud\Support\Common\SupportRole_Role::class);

