<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/cigar.proto

namespace Google\Genomics\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Genomics\V1\CigarUnit\Operation instead.
     * @deprecated
     */
    class CigarUnit_Operation {}
}
class_exists(CigarUnit\Operation::class);
@trigger_error('Google\Genomics\V1\CigarUnit_Operation is deprecated and will be removed in the next major release. Use Google\Genomics\V1\CigarUnit\Operation instead', E_USER_DEPRECATED);

