<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/datasets.proto

namespace Google\Genomics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.genomics.v1.CreateDatasetRequest</code>
 */
class CreateDatasetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The dataset to be created. Must contain projectId and name.
     *
     * Generated from protobuf field <code>.google.genomics.v1.Dataset dataset = 1;</code>
     */
    private $dataset = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Genomics\V1\Dataset $dataset
     *           The dataset to be created. Must contain projectId and name.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Genomics\V1\Datasets::initOnce();
        parent::__construct($data);
    }

    /**
     * The dataset to be created. Must contain projectId and name.
     *
     * Generated from protobuf field <code>.google.genomics.v1.Dataset dataset = 1;</code>
     * @return \Google\Genomics\V1\Dataset
     */
    public function getDataset()
    {
        return $this->dataset;
    }

    /**
     * The dataset to be created. Must contain projectId and name.
     *
     * Generated from protobuf field <code>.google.genomics.v1.Dataset dataset = 1;</code>
     * @param \Google\Genomics\V1\Dataset $var
     * @return $this
     */
    public function setDataset($var)
    {
        GPBUtil::checkMessage($var, \Google\Genomics\V1\Dataset::class);
        $this->dataset = $var;

        return $this;
    }

}

