<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/reads.proto

namespace Google\Genomics\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Genomics\V1\ImportReadGroupSetsRequest\PartitionStrategy instead.
     * @deprecated
     */
    class ImportReadGroupSetsRequest_PartitionStrategy {}
}
class_exists(ImportReadGroupSetsRequest\PartitionStrategy::class);
@trigger_error('Google\Genomics\V1\ImportReadGroupSetsRequest_PartitionStrategy is deprecated and will be removed in the next major release. Use Google\Genomics\V1\ImportReadGroupSetsRequest\PartitionStrategy instead', E_USER_DEPRECATED);

