<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/support/v1alpha1/cloud_support.proto

namespace Google\Cloud\Support\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for `ListSupportAccount`.
 *
 * Generated from protobuf message <code>google.cloud.support.v1alpha1.ListSupportAccountsRequest</code>
 */
class ListSupportAccountsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The filter applied to search results. It only supports filtering a support
     * account list by a cloud_resource. For example, to filter results by support
     * accounts associated with an Organization, its value should be:
     * "cloud_resource:organizations/<organization_id>"
     *
     * Generated from protobuf field <code>string filter = 1;</code>
     */
    private $filter = '';
    /**
     * Maximum number of accounts fetched with each request.
     *
     * Generated from protobuf field <code>int64 page_size = 2;</code>
     */
    private $page_size = 0;
    /**
     * A token identifying the page of results to return. If unspecified, the
     * first page is retrieved.
     *
     * Generated from protobuf field <code>string page_token = 3;</code>
     */
    private $page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $filter
     *           The filter applied to search results. It only supports filtering a support
     *           account list by a cloud_resource. For example, to filter results by support
     *           accounts associated with an Organization, its value should be:
     *           "cloud_resource:organizations/<organization_id>"
     *     @type int|string $page_size
     *           Maximum number of accounts fetched with each request.
     *     @type string $page_token
     *           A token identifying the page of results to return. If unspecified, the
     *           first page is retrieved.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Support\V1Alpha1\CloudSupport::initOnce();
        parent::__construct($data);
    }

    /**
     * The filter applied to search results. It only supports filtering a support
     * account list by a cloud_resource. For example, to filter results by support
     * accounts associated with an Organization, its value should be:
     * "cloud_resource:organizations/<organization_id>"
     *
     * Generated from protobuf field <code>string filter = 1;</code>
     * @return string
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * The filter applied to search results. It only supports filtering a support
     * account list by a cloud_resource. For example, to filter results by support
     * accounts associated with an Organization, its value should be:
     * "cloud_resource:organizations/<organization_id>"
     *
     * Generated from protobuf field <code>string filter = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkString($var, True);
        $this->filter = $var;

        return $this;
    }

    /**
     * Maximum number of accounts fetched with each request.
     *
     * Generated from protobuf field <code>int64 page_size = 2;</code>
     * @return int|string
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Maximum number of accounts fetched with each request.
     *
     * Generated from protobuf field <code>int64 page_size = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * A token identifying the page of results to return. If unspecified, the
     * first page is retrieved.
     *
     * Generated from protobuf field <code>string page_token = 3;</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * A token identifying the page of results to return. If unspecified, the
     * first page is retrieved.
     *
     * Generated from protobuf field <code>string page_token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

}

