<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/support/v1alpha1/cloud_support.proto

namespace Google\Cloud\Support\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response message for `ListComments` method.
 *
 * Generated from protobuf message <code>google.cloud.support.v1alpha1.ListCommentsResponse</code>
 */
class ListCommentsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of comments.
     *
     * Generated from protobuf field <code>repeated .google.cloud.support.common.Comment comments = 1;</code>
     */
    private $comments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\Support\Common\Comment[]|\Google\Protobuf\Internal\RepeatedField $comments
     *           A list of comments.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Support\V1Alpha1\CloudSupport::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of comments.
     *
     * Generated from protobuf field <code>repeated .google.cloud.support.common.Comment comments = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * A list of comments.
     *
     * Generated from protobuf field <code>repeated .google.cloud.support.common.Comment comments = 1;</code>
     * @param \Google\Cloud\Support\Common\Comment[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setComments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Support\Common\Comment::class);
        $this->comments = $arr;

        return $this;
    }

}

