<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/ml/v1/job_service.proto

namespace Google\Cloud\Ml\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Ml\V1\Job\State instead.
     * @deprecated
     */
    class Job_State {}
}
class_exists(Job\State::class);
@trigger_error('Google\Cloud\Ml\V1\Job_State is deprecated and will be removed in the next major release. Use Google\Cloud\Ml\V1\Job\State instead', E_USER_DEPRECATED);

