<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/ml/v1/model_service.proto

namespace Google\Cloud\Ml\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response message for the ListModels method.
 *
 * Generated from protobuf message <code>google.cloud.ml.v1.ListModelsResponse</code>
 */
class ListModelsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of models.
     *
     * Generated from protobuf field <code>repeated .google.cloud.ml.v1.Model models = 1;</code>
     */
    private $models;
    /**
     * Optional. Pass this token as the `page_token` field of the request for a
     * subsequent call.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    private $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\Ml\V1\Model[]|\Google\Protobuf\Internal\RepeatedField $models
     *           The list of models.
     *     @type string $next_page_token
     *           Optional. Pass this token as the `page_token` field of the request for a
     *           subsequent call.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Ml\V1\ModelService::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of models.
     *
     * Generated from protobuf field <code>repeated .google.cloud.ml.v1.Model models = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getModels()
    {
        return $this->models;
    }

    /**
     * The list of models.
     *
     * Generated from protobuf field <code>repeated .google.cloud.ml.v1.Model models = 1;</code>
     * @param \Google\Cloud\Ml\V1\Model[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setModels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Ml\V1\Model::class);
        $this->models = $arr;

        return $this;
    }

    /**
     * Optional. Pass this token as the `page_token` field of the request for a
     * subsequent call.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Optional. Pass this token as the `page_token` field of the request for a
     * subsequent call.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

