<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/ml/v1/job_service.proto

namespace Google\Cloud\Ml\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Ml\V1\TrainingInput\ScaleTier instead.
     * @deprecated
     */
    class TrainingInput_ScaleTier {}
}
class_exists(TrainingInput\ScaleTier::class);
@trigger_error('Google\Cloud\Ml\V1\TrainingInput_ScaleTier is deprecated and will be removed in the next major release. Use Google\Cloud\Ml\V1\TrainingInput\ScaleTier instead', E_USER_DEPRECATED);

