<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/cloudbuild/v1/cloudbuild.proto

namespace Google\Devtools\Cloudbuild\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Configuration for an automated build in response to source repository
 * changes.
 *
 * Generated from protobuf message <code>google.devtools.cloudbuild.v1.BuildTrigger</code>
 */
class BuildTrigger extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique identifier of the trigger.
     * &#64;OutputOnly
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Human-readable description of this trigger.
     *
     * Generated from protobuf field <code>string description = 10;</code>
     */
    private $description = '';
    /**
     * Template describing the types of source changes to trigger a build.
     * Branch and tag names in trigger templates are interpreted as regular
     * expressions. Any branch or tag change that matches that regular expression
     * will trigger a build.
     *
     * Generated from protobuf field <code>.google.devtools.cloudbuild.v1.RepoSource trigger_template = 7;</code>
     */
    private $trigger_template = null;
    /**
     * Time when the trigger was created.
     * &#64;OutputOnly
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 5;</code>
     */
    private $create_time = null;
    /**
     * If true, the trigger will never result in a build.
     *
     * Generated from protobuf field <code>bool disabled = 9;</code>
     */
    private $disabled = false;
    /**
     * Substitutions data for Build resource.
     *
     * Generated from protobuf field <code>map<string, string> substitutions = 11;</code>
     */
    private $substitutions;
    protected $build_template;

    public function __construct() {
        \GPBMetadata\Google\Devtools\Cloudbuild\V1\Cloudbuild::initOnce();
        parent::__construct();
    }

    /**
     * Unique identifier of the trigger.
     * &#64;OutputOnly
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Unique identifier of the trigger.
     * &#64;OutputOnly
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Human-readable description of this trigger.
     *
     * Generated from protobuf field <code>string description = 10;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Human-readable description of this trigger.
     *
     * Generated from protobuf field <code>string description = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Template describing the types of source changes to trigger a build.
     * Branch and tag names in trigger templates are interpreted as regular
     * expressions. Any branch or tag change that matches that regular expression
     * will trigger a build.
     *
     * Generated from protobuf field <code>.google.devtools.cloudbuild.v1.RepoSource trigger_template = 7;</code>
     * @return \Google\Devtools\Cloudbuild\V1\RepoSource
     */
    public function getTriggerTemplate()
    {
        return $this->trigger_template;
    }

    /**
     * Template describing the types of source changes to trigger a build.
     * Branch and tag names in trigger templates are interpreted as regular
     * expressions. Any branch or tag change that matches that regular expression
     * will trigger a build.
     *
     * Generated from protobuf field <code>.google.devtools.cloudbuild.v1.RepoSource trigger_template = 7;</code>
     * @param \Google\Devtools\Cloudbuild\V1\RepoSource $var
     * @return $this
     */
    public function setTriggerTemplate($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Cloudbuild\V1\RepoSource::class);
        $this->trigger_template = $var;

        return $this;
    }

    /**
     * Contents of the build template.
     *
     * Generated from protobuf field <code>.google.devtools.cloudbuild.v1.Build build = 4;</code>
     * @return \Google\Devtools\Cloudbuild\V1\Build
     */
    public function getBuild()
    {
        return $this->readOneof(4);
    }

    /**
     * Contents of the build template.
     *
     * Generated from protobuf field <code>.google.devtools.cloudbuild.v1.Build build = 4;</code>
     * @param \Google\Devtools\Cloudbuild\V1\Build $var
     * @return $this
     */
    public function setBuild($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Cloudbuild\V1\Build::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Path, from the source root, to a file whose contents is used for the
     * template.
     *
     * Generated from protobuf field <code>string filename = 8;</code>
     * @return string
     */
    public function getFilename()
    {
        return $this->readOneof(8);
    }

    /**
     * Path, from the source root, to a file whose contents is used for the
     * template.
     *
     * Generated from protobuf field <code>string filename = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setFilename($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Time when the trigger was created.
     * &#64;OutputOnly
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 5;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Time when the trigger was created.
     * &#64;OutputOnly
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 5;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->create_time = $var;

        return $this;
    }

    /**
     * If true, the trigger will never result in a build.
     *
     * Generated from protobuf field <code>bool disabled = 9;</code>
     * @return bool
     */
    public function getDisabled()
    {
        return $this->disabled;
    }

    /**
     * If true, the trigger will never result in a build.
     *
     * Generated from protobuf field <code>bool disabled = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisabled($var)
    {
        GPBUtil::checkBool($var);
        $this->disabled = $var;

        return $this;
    }

    /**
     * Substitutions data for Build resource.
     *
     * Generated from protobuf field <code>map<string, string> substitutions = 11;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSubstitutions()
    {
        return $this->substitutions;
    }

    /**
     * Substitutions data for Build resource.
     *
     * Generated from protobuf field <code>map<string, string> substitutions = 11;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSubstitutions($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->substitutions = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getBuildTemplate()
    {
        return $this->whichOneof("build_template");
    }

}

