<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/appengine/v1/appengine.proto

namespace Google\Appengine\V1;

/**
 * Fields that should be returned when [Version][google.appengine.v1.Version] resources
 * are retreived.
 *
 * Protobuf type <code>google.appengine.v1.VersionView</code>
 */
class VersionView
{
    /**
     * Basic version information including scaling and inbound services,
     * but not detailed deployment information.
     *
     * Generated from protobuf enum <code>BASIC = 0;</code>
     */
    const BASIC = 0;
    /**
     * The information from `BASIC`, plus detailed information about the
     * deployment. This format is required when creating resources, but
     * is not returned in `Get` or `List` by default.
     *
     * Generated from protobuf enum <code>FULL = 1;</code>
     */
    const FULL = 1;
}

