<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/support/common.proto

namespace Google\Cloud\Support\Common;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Support\Common\SupportAccount\State instead.
     * @deprecated
     */
    class SupportAccount_State {}
}
class_exists(SupportAccount\State::class);
@trigger_error('Google\Cloud\Support\Common\SupportAccount_State is deprecated and will be removed in the next major release. Use Google\Cloud\Support\Common\SupportAccount\State instead', E_USER_DEPRECATED);

