<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/admin/v1/iam.proto

namespace Google\Iam\Admin\V1\Permission;

/**
 * The state of the permission with regards to custom roles.
 *
 * Protobuf type <code>google.iam.admin.v1.Permission.CustomRolesSupportLevel</code>
 */
class CustomRolesSupportLevel
{
    /**
     * Permission is fully supported for custom role use.
     *
     * Generated from protobuf enum <code>SUPPORTED = 0;</code>
     */
    const SUPPORTED = 0;
    /**
     * Permission is being tested to check custom role compatibility.
     *
     * Generated from protobuf enum <code>TESTING = 1;</code>
     */
    const TESTING = 1;
    /**
     * Permission is not supported for custom role use.
     *
     * Generated from protobuf enum <code>NOT_SUPPORTED = 2;</code>
     */
    const NOT_SUPPORTED = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CustomRolesSupportLevel::class, \Google\Iam\Admin\V1\Permission_CustomRolesSupportLevel::class);

