<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/appengine/v1/audit_data.proto

namespace Google\Appengine\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Detailed information about CreateVersion call.
 *
 * Generated from protobuf message <code>google.appengine.v1.CreateVersionMethod</code>
 */
class CreateVersionMethod extends \Google\Protobuf\Internal\Message
{
    /**
     * Create version request.
     *
     * Generated from protobuf field <code>.google.appengine.v1.CreateVersionRequest request = 1;</code>
     */
    private $request = null;

    public function __construct() {
        \GPBMetadata\Google\Appengine\V1\AuditData::initOnce();
        parent::__construct();
    }

    /**
     * Create version request.
     *
     * Generated from protobuf field <code>.google.appengine.v1.CreateVersionRequest request = 1;</code>
     * @return \Google\Appengine\V1\CreateVersionRequest
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Create version request.
     *
     * Generated from protobuf field <code>.google.appengine.v1.CreateVersionRequest request = 1;</code>
     * @param \Google\Appengine\V1\CreateVersionRequest $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Google\Appengine\V1\CreateVersionRequest::class);
        $this->request = $var;

        return $this;
    }

}

