<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/support/common.proto

namespace Google\Cloud\Support\Common\SupportAccount;

/**
 * Pricing model applicable to this support account.
 *
 * Protobuf type <code>google.cloud.support.common.SupportAccount.PricingModel</code>
 */
class PricingModel
{
    /**
     * This account is subscribed to an unknown pricing model.
     *
     * Generated from protobuf enum <code>PRICING_MODEL_UNKNOWN = 0;</code>
     */
    const PRICING_MODEL_UNKNOWN = 0;
    /**
     * Package based pricing (Platinum, Gold, Silver, Bronze).
     *
     * Generated from protobuf enum <code>PACKAGES = 1;</code>
     */
    const PACKAGES = 1;
    /**
     * Support charges are calculated based on user seats a.k.a,
     * "Pick Your Team" model.
     *
     * Generated from protobuf enum <code>USER_ROLES = 2;</code>
     */
    const USER_ROLES = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PricingModel::class, \Google\Cloud\Support\Common\SupportAccount_PricingModel::class);

