<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/home/graph/v1/homegraph.proto

namespace Google\Home\Graph\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response type for Query call. This should follow the same format as AoG
 * action.devices.QUERY response
 * (https://developers.google.com/actions/smarthome/create-app#actiondevicesquery).
 *
 * Generated from protobuf message <code>google.home.graph.v1.QueryResponse</code>
 */
class QueryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Request ID used for debugging. Copied from the request.
     *
     * Generated from protobuf field <code>string request_id = 1;</code>
     */
    private $request_id = '';
    /**
     * Device states for the devices given in the request.
     *
     * Generated from protobuf field <code>.google.home.graph.v1.QueryResponsePayload payload = 2;</code>
     */
    private $payload = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $request_id
     *           Request ID used for debugging. Copied from the request.
     *     @type \Google\Home\Graph\V1\QueryResponsePayload $payload
     *           Device states for the devices given in the request.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Home\Graph\V1\Homegraph::initOnce();
        parent::__construct($data);
    }

    /**
     * Request ID used for debugging. Copied from the request.
     *
     * Generated from protobuf field <code>string request_id = 1;</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * Request ID used for debugging. Copied from the request.
     *
     * Generated from protobuf field <code>string request_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Device states for the devices given in the request.
     *
     * Generated from protobuf field <code>.google.home.graph.v1.QueryResponsePayload payload = 2;</code>
     * @return \Google\Home\Graph\V1\QueryResponsePayload
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Device states for the devices given in the request.
     *
     * Generated from protobuf field <code>.google.home.graph.v1.QueryResponsePayload payload = 2;</code>
     * @param \Google\Home\Graph\V1\QueryResponsePayload $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Google\Home\Graph\V1\QueryResponsePayload::class);
        $this->payload = $var;

        return $this;
    }

}

