<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/privacy/dlp/v2beta1/dlp.proto

namespace Google\Cloud\Dlp\V2beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for the list of info types belonging to a given category,
 * or all supported info types if no category is specified.
 *
 * Generated from protobuf message <code>google.privacy.dlp.v2beta1.ListInfoTypesRequest</code>
 */
class ListInfoTypesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Category name as returned by ListRootCategories.
     *
     * Generated from protobuf field <code>string category = 1;</code>
     */
    private $category = '';
    /**
     * Optional BCP-47 language code for localized info type friendly
     * names. If omitted, or if localized strings are not available,
     * en-US strings will be returned.
     *
     * Generated from protobuf field <code>string language_code = 2;</code>
     */
    private $language_code = '';

    public function __construct() {
        \GPBMetadata\Google\Privacy\Dlp\V2Beta1\Dlp::initOnce();
        parent::__construct();
    }

    /**
     * Category name as returned by ListRootCategories.
     *
     * Generated from protobuf field <code>string category = 1;</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Category name as returned by ListRootCategories.
     *
     * Generated from protobuf field <code>string category = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     * Optional BCP-47 language code for localized info type friendly
     * names. If omitted, or if localized strings are not available,
     * en-US strings will be returned.
     *
     * Generated from protobuf field <code>string language_code = 2;</code>
     * @return string
     */
    public function getLanguageCode()
    {
        return $this->language_code;
    }

    /**
     * Optional BCP-47 language code for localized info type friendly
     * names. If omitted, or if localized strings are not available,
     * en-US strings will be returned.
     *
     * Generated from protobuf field <code>string language_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguageCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_code = $var;

        return $this;
    }

}

