<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/cloudbuild/v1/cloudbuild.proto

namespace Google\Devtools\Cloudbuild\V1\BuildOptions;

/**
 * Supported VM sizes.
 *
 * Protobuf type <code>google.devtools.cloudbuild.v1.BuildOptions.MachineType</code>
 */
class MachineType
{
    /**
     * Standard machine type.
     *
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * Highcpu machine with 8 CPUs.
     *
     * Generated from protobuf enum <code>N1_HIGHCPU_8 = 1;</code>
     */
    const N1_HIGHCPU_8 = 1;
    /**
     * Highcpu machine with 32 CPUs.
     *
     * Generated from protobuf enum <code>N1_HIGHCPU_32 = 2;</code>
     */
    const N1_HIGHCPU_32 = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MachineType::class, \Google\Devtools\Cloudbuild\V1\BuildOptions_MachineType::class);

