<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/rpcmessages.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to get one or more photos.
 * By default
 * - does not return the download URL for the photo bytes.
 * Parameters:
 * - 'view' controls if the download URL for the photo bytes will be returned.
 *
 * Generated from protobuf message <code>google.streetview.publish.v1.BatchGetPhotosRequest</code>
 */
class BatchGetPhotosRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. IDs of the photos.
     *
     * Generated from protobuf field <code>repeated string photo_ids = 1;</code>
     */
    private $photo_ids;
    /**
     * Specifies if a download URL for the photo bytes should be returned in the
     * Photo response.
     *
     * Generated from protobuf field <code>.google.streetview.publish.v1.PhotoView view = 2;</code>
     */
    private $view = 0;

    public function __construct() {
        \GPBMetadata\Google\Streetview\Publish\V1\Rpcmessages::initOnce();
        parent::__construct();
    }

    /**
     * Required. IDs of the photos.
     *
     * Generated from protobuf field <code>repeated string photo_ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPhotoIds()
    {
        return $this->photo_ids;
    }

    /**
     * Required. IDs of the photos.
     *
     * Generated from protobuf field <code>repeated string photo_ids = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPhotoIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->photo_ids = $arr;

        return $this;
    }

    /**
     * Specifies if a download URL for the photo bytes should be returned in the
     * Photo response.
     *
     * Generated from protobuf field <code>.google.streetview.publish.v1.PhotoView view = 2;</code>
     * @return int
     */
    public function getView()
    {
        return $this->view;
    }

    /**
     * Specifies if a download URL for the photo bytes should be returned in the
     * Photo response.
     *
     * Generated from protobuf field <code>.google.streetview.publish.v1.PhotoView view = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setView($var)
    {
        GPBUtil::checkEnum($var, \Google\Streetview\Publish\V1\PhotoView::class);
        $this->view = $var;

        return $this;
    }

}

