<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1alpha2/pipelines.proto

namespace Google\Genomics\V1alpha2;

if (false) {
    /**
     * This class is deprecated. Use Google\Genomics\V1alpha2\ControllerConfig\RepeatedString instead.
     * @deprecated
     */
    class ControllerConfig_RepeatedString {}
}
class_exists(ControllerConfig\RepeatedString::class);
@trigger_error('Google\Genomics\V1alpha2\ControllerConfig_RepeatedString is deprecated and will be removed in the next major release. Use Google\Genomics\V1alpha2\ControllerConfig\RepeatedString instead', E_USER_DEPRECATED);

