<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/remoteexecution/v1test/remote_execution.proto

namespace Google\Devtools\Remoteexecution\V1test;

/**
 * The current stage of execution.
 *
 * Protobuf enum <code>Google\Devtools\Remoteexecution\V1test\ExecuteOperationMetadata\Stage</code>
 */
class ExecuteOperationMetadata_Stage
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Checking the result against the cache.
     *
     * Generated from protobuf enum <code>CACHE_CHECK = 1;</code>
     */
    const CACHE_CHECK = 1;
    /**
     * Currently idle, awaiting a free machine to execute.
     *
     * Generated from protobuf enum <code>QUEUED = 2;</code>
     */
    const QUEUED = 2;
    /**
     * Currently being executed by a worker.
     *
     * Generated from protobuf enum <code>EXECUTING = 3;</code>
     */
    const EXECUTING = 3;
    /**
     * Finished execution.
     *
     * Generated from protobuf enum <code>COMPLETED = 4;</code>
     */
    const COMPLETED = 4;
}

