<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/remoteexecution/v1test/remote_execution.proto

namespace Google\Devtools\Remoteexecution\V1test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An `OutputFile` is similar to a
 * [FileNode][google.devtools.remoteexecution.v1test.FileNode], but it is
 * tailored for output as part of an `ActionResult`. It allows a full file path
 * rather than only a name, and allows the server to include content inline.
 * `OutputFile` is binary-compatible with `FileNode`.
 *
 * Generated from protobuf message <code>google.devtools.remoteexecution.v1test.OutputFile</code>
 */
class OutputFile extends \Google\Protobuf\Internal\Message
{
    /**
     * The full path of the file relative to the input root, including the
     * filename. The path separator is a forward slash `/`.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    private $path = '';
    /**
     * The digest of the file's content.
     *
     * Generated from protobuf field <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
     */
    private $digest = null;
    /**
     * The raw content of the file.
     * This field may be used by the server to provide the content of a file
     * inline in an
     * [ActionResult][google.devtools.remoteexecution.v1test.ActionResult] and
     * avoid requiring that the client make a separate call to
     * [ContentAddressableStorage.GetBlob] to retrieve it.
     * The client SHOULD NOT assume that it will get raw content with any request,
     * and always be prepared to retrieve it via `digest`.
     *
     * Generated from protobuf field <code>bytes content = 3;</code>
     */
    private $content = '';
    /**
     * True if file is executable, false otherwise.
     *
     * Generated from protobuf field <code>bool is_executable = 4;</code>
     */
    private $is_executable = false;

    public function __construct() {
        \GPBMetadata\Google\Devtools\Remoteexecution\V1Test\RemoteExecution::initOnce();
        parent::__construct();
    }

    /**
     * The full path of the file relative to the input root, including the
     * filename. The path separator is a forward slash `/`.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * The full path of the file relative to the input root, including the
     * filename. The path separator is a forward slash `/`.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * The digest of the file's content.
     *
     * Generated from protobuf field <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
     * @return \Google\Devtools\Remoteexecution\V1test\Digest
     */
    public function getDigest()
    {
        return $this->digest;
    }

    /**
     * The digest of the file's content.
     *
     * Generated from protobuf field <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
     * @param \Google\Devtools\Remoteexecution\V1test\Digest $var
     * @return $this
     */
    public function setDigest($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Remoteexecution\V1test\Digest::class);
        $this->digest = $var;

        return $this;
    }

    /**
     * The raw content of the file.
     * This field may be used by the server to provide the content of a file
     * inline in an
     * [ActionResult][google.devtools.remoteexecution.v1test.ActionResult] and
     * avoid requiring that the client make a separate call to
     * [ContentAddressableStorage.GetBlob] to retrieve it.
     * The client SHOULD NOT assume that it will get raw content with any request,
     * and always be prepared to retrieve it via `digest`.
     *
     * Generated from protobuf field <code>bytes content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * The raw content of the file.
     * This field may be used by the server to provide the content of a file
     * inline in an
     * [ActionResult][google.devtools.remoteexecution.v1test.ActionResult] and
     * avoid requiring that the client make a separate call to
     * [ContentAddressableStorage.GetBlob] to retrieve it.
     * The client SHOULD NOT assume that it will get raw content with any request,
     * and always be prepared to retrieve it via `digest`.
     *
     * Generated from protobuf field <code>bytes content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->content = $var;

        return $this;
    }

    /**
     * True if file is executable, false otherwise.
     *
     * Generated from protobuf field <code>bool is_executable = 4;</code>
     * @return bool
     */
    public function getIsExecutable()
    {
        return $this->is_executable;
    }

    /**
     * True if file is executable, false otherwise.
     *
     * Generated from protobuf field <code>bool is_executable = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsExecutable($var)
    {
        GPBUtil::checkBool($var);
        $this->is_executable = $var;

        return $this;
    }

}

