<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/datastore/admin/v1/datastore_admin.proto

namespace Google\Datastore\Admin\V1;

/**
 * Operation types.
 *
 * Protobuf type <code>google.datastore.admin.v1.OperationType</code>
 */
class OperationType
{
    /**
     * Unspecified.
     *
     * Generated from protobuf enum <code>OPERATION_TYPE_UNSPECIFIED = 0;</code>
     */
    const OPERATION_TYPE_UNSPECIFIED = 0;
    /**
     * ExportEntities.
     *
     * Generated from protobuf enum <code>EXPORT_ENTITIES = 1;</code>
     */
    const EXPORT_ENTITIES = 1;
    /**
     * ImportEntities.
     *
     * Generated from protobuf enum <code>IMPORT_ENTITIES = 2;</code>
     */
    const IMPORT_ENTITIES = 2;
    /**
     * CreateIndex.
     *
     * Generated from protobuf enum <code>CREATE_INDEX = 3;</code>
     */
    const CREATE_INDEX = 3;
    /**
     * DeleteIndex.
     *
     * Generated from protobuf enum <code>DELETE_INDEX = 4;</code>
     */
    const DELETE_INDEX = 4;
}

