<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/websecurityscanner/v1alpha/scan_config.proto

namespace Google\Cloud\Websecurityscanner\V1alpha;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Websecurityscanner\V1alpha\ScanConfig\TargetPlatform instead.
     * @deprecated
     */
    class ScanConfig_TargetPlatform {}
}
class_exists(ScanConfig\TargetPlatform::class);
@trigger_error('Google\Cloud\Websecurityscanner\V1alpha\ScanConfig_TargetPlatform is deprecated and will be removed in the next major release. Use Google\Cloud\Websecurityscanner\V1alpha\ScanConfig\TargetPlatform instead', E_USER_DEPRECATED);

