<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/resourcemanager/v2/folders.proto

namespace Google\Cloud\ResourceManager\V2;

/**
 * The type of operation that failed.
 *
 * Protobuf enum <code>Google\Cloud\Resourcemanager\V2\FolderOperation\OperationType</code>
 */
class FolderOperation_OperationType
{
    /**
     * Operation type not specified.
     *
     * Generated from protobuf enum <code>OPERATION_TYPE_UNSPECIFIED = 0;</code>
     */
    const OPERATION_TYPE_UNSPECIFIED = 0;
    /**
     * A create folder operation.
     *
     * Generated from protobuf enum <code>CREATE = 1;</code>
     */
    const CREATE = 1;
    /**
     * A move folder operation.
     *
     * Generated from protobuf enum <code>MOVE = 2;</code>
     */
    const MOVE = 2;
}

