<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/resourcemanager/v2/folders.proto

namespace Google\Cloud\ResourceManager\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The GetFolder request message.
 *
 * Generated from protobuf message <code>google.cloud.resourcemanager.v2.GetFolderRequest</code>
 */
class GetFolderRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The resource name of the Folder to retrieve.
     * Must be of the form `folders/{folder_id}`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';

    public function __construct() {
        \GPBMetadata\Google\Cloud\Resourcemanager\V2\Folders::initOnce();
        parent::__construct();
    }

    /**
     * The resource name of the Folder to retrieve.
     * Must be of the form `folders/{folder_id}`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The resource name of the Folder to retrieve.
     * Must be of the form `folders/{folder_id}`.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

