<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/support/common.proto

namespace Google\Cloud\Support\Common\CustomerIssue;

/**
 * The status of a customer issue.
 *
 * Protobuf type <code>google.cloud.support.common.CustomerIssue.IssueState</code>
 */
class IssueState
{
    /**
     * Issue in an unknown state.
     *
     * Generated from protobuf enum <code>ISSUE_STATE_UNSPECIFIED = 0;</code>
     */
    const ISSUE_STATE_UNSPECIFIED = 0;
    /**
     * Issue is currently open but the work on it has not been started.
     *
     * Generated from protobuf enum <code>OPEN = 1;</code>
     */
    const OPEN = 1;
    /**
     * Issue is currently being worked on.
     *
     * Generated from protobuf enum <code>IN_PROGRESS = 2;</code>
     */
    const IN_PROGRESS = 2;
    /**
     * Issue is fixed.
     *
     * Generated from protobuf enum <code>FIXED = 3;</code>
     */
    const FIXED = 3;
    /**
     * Issue has been marked as invalid.
     *
     * Generated from protobuf enum <code>WONT_FIX = 4;</code>
     */
    const WONT_FIX = 4;
    /**
     * Issue verified and in production.
     *
     * Generated from protobuf enum <code>VERIFIED = 5;</code>
     */
    const VERIFIED = 5;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(IssueState::class, \Google\Cloud\Support\Common\CustomerIssue_IssueState::class);

