<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v0/errors/id_error.proto

namespace Google\Ads\GoogleAds\V0\Errors;

class IdError
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abe020a2d676f6f676c652f6164732f676f6f676c656164732f76302f65" .
            "72726f72732f69645f6572726f722e70726f746f121e676f6f676c652e61" .
            "64732e676f6f676c656164732e76302e6572726f727322450a0b49644572" .
            "726f72456e756d22360a0749644572726f72120f0a0b554e535045434946" .
            "4945441000120b0a07554e4b4e4f574e1001120d0a094e4f545f464f554e" .
            "441002429d010a22636f6d2e676f6f676c652e6164732e676f6f676c6561" .
            "64732e76302e6572726f7273420c49644572726f7250726f746f5001a202" .
            "03474141aa021e476f6f676c652e4164732e476f6f676c654164732e5630" .
            "2e4572726f7273ca021e476f6f676c655c4164735c476f6f676c65416473" .
            "5c56305c4572726f7273e2021e476f6f676c655c4164735c476f6f676c65" .
            "4164735c56305c4572726f7273620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

