<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/bigtable/v1/bigtable_service_messages.proto

namespace Google\Bigtable\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response message for BigtableService.MutateRows.
 *
 * Generated from protobuf message <code>google.bigtable.v1.MutateRowsResponse</code>
 */
class MutateRowsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The results for each Entry from the request, presented in the order
     * in which the entries were originally given.
     * Depending on how requests are batched during execution, it is possible
     * for one Entry to fail due to an error with another Entry. In the event
     * that this occurs, the same error will be reported for both entries.
     *
     * Generated from protobuf field <code>repeated .google.rpc.Status statuses = 1;</code>
     */
    private $statuses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Rpc\Status[]|\Google\Protobuf\Internal\RepeatedField $statuses
     *           The results for each Entry from the request, presented in the order
     *           in which the entries were originally given.
     *           Depending on how requests are batched during execution, it is possible
     *           for one Entry to fail due to an error with another Entry. In the event
     *           that this occurs, the same error will be reported for both entries.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Bigtable\V1\BigtableServiceMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * The results for each Entry from the request, presented in the order
     * in which the entries were originally given.
     * Depending on how requests are batched during execution, it is possible
     * for one Entry to fail due to an error with another Entry. In the event
     * that this occurs, the same error will be reported for both entries.
     *
     * Generated from protobuf field <code>repeated .google.rpc.Status statuses = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStatuses()
    {
        return $this->statuses;
    }

    /**
     * The results for each Entry from the request, presented in the order
     * in which the entries were originally given.
     * Depending on how requests are batched during execution, it is possible
     * for one Entry to fail due to an error with another Entry. In the event
     * that this occurs, the same error will be reported for both entries.
     *
     * Generated from protobuf field <code>repeated .google.rpc.Status statuses = 1;</code>
     * @param \Google\Rpc\Status[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStatuses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Rpc\Status::class);
        $this->statuses = $arr;

        return $this;
    }

}

