<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/bigtable/v1/bigtable_service_messages.proto

namespace Google\Bigtable\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response message for BigtableService.ReadRows.
 *
 * Generated from protobuf message <code>google.bigtable.v1.ReadRowsResponse</code>
 */
class ReadRowsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The key of the row for which we're receiving data.
     * Results will be received in increasing row key order, unless
     * "allow_row_interleaving" was specified in the request.
     *
     * Generated from protobuf field <code>bytes row_key = 1;</code>
     */
    private $row_key = '';
    /**
     * One or more chunks of the row specified by "row_key".
     *
     * Generated from protobuf field <code>repeated .google.bigtable.v1.ReadRowsResponse.Chunk chunks = 2;</code>
     */
    private $chunks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $row_key
     *           The key of the row for which we're receiving data.
     *           Results will be received in increasing row key order, unless
     *           "allow_row_interleaving" was specified in the request.
     *     @type \Google\Bigtable\V1\ReadRowsResponse\Chunk[]|\Google\Protobuf\Internal\RepeatedField $chunks
     *           One or more chunks of the row specified by "row_key".
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Bigtable\V1\BigtableServiceMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * The key of the row for which we're receiving data.
     * Results will be received in increasing row key order, unless
     * "allow_row_interleaving" was specified in the request.
     *
     * Generated from protobuf field <code>bytes row_key = 1;</code>
     * @return string
     */
    public function getRowKey()
    {
        return $this->row_key;
    }

    /**
     * The key of the row for which we're receiving data.
     * Results will be received in increasing row key order, unless
     * "allow_row_interleaving" was specified in the request.
     *
     * Generated from protobuf field <code>bytes row_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRowKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->row_key = $var;

        return $this;
    }

    /**
     * One or more chunks of the row specified by "row_key".
     *
     * Generated from protobuf field <code>repeated .google.bigtable.v1.ReadRowsResponse.Chunk chunks = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChunks()
    {
        return $this->chunks;
    }

    /**
     * One or more chunks of the row specified by "row_key".
     *
     * Generated from protobuf field <code>repeated .google.bigtable.v1.ReadRowsResponse.Chunk chunks = 2;</code>
     * @param \Google\Bigtable\V1\ReadRowsResponse\Chunk[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChunks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Bigtable\V1\ReadRowsResponse\Chunk::class);
        $this->chunks = $arr;

        return $this;
    }

}

