<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/bigtable/v1/bigtable_data.proto

namespace Google\Bigtable\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Bigtable\V1\RowFilter\Chain instead.
     * @deprecated
     */
    class RowFilter_Chain {}
}
class_exists(RowFilter\Chain::class);
@trigger_error('Google\Bigtable\V1\RowFilter_Chain is deprecated and will be removed in the next major release. Use Google\Bigtable\V1\RowFilter\Chain instead', E_USER_DEPRECATED);

