<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/remoteexecution/v1test/remote_execution.proto

namespace Google\Devtools\Remoteexecution\V1test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A `LogFile` is a log stored in the CAS.
 *
 * Generated from protobuf message <code>google.devtools.remoteexecution.v1test.LogFile</code>
 */
class LogFile extends \Google\Protobuf\Internal\Message
{
    /**
     * The digest of the log contents.
     *
     * Generated from protobuf field <code>.google.devtools.remoteexecution.v1test.Digest digest = 1;</code>
     */
    private $digest = null;
    /**
     * This is a hint as to the purpose of the log, and is set to true if the log
     * is human-readable text that can be usefully displayed to a user, and false
     * otherwise. For instance, if a command-line client wishes to print the
     * server logs to the terminal for a failed action, this allows it to avoid
     * displaying a binary file.
     *
     * Generated from protobuf field <code>bool human_readable = 2;</code>
     */
    private $human_readable = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Devtools\Remoteexecution\V1test\Digest $digest
     *           The digest of the log contents.
     *     @type bool $human_readable
     *           This is a hint as to the purpose of the log, and is set to true if the log
     *           is human-readable text that can be usefully displayed to a user, and false
     *           otherwise. For instance, if a command-line client wishes to print the
     *           server logs to the terminal for a failed action, this allows it to avoid
     *           displaying a binary file.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Devtools\Remoteexecution\V1Test\RemoteExecution::initOnce();
        parent::__construct($data);
    }

    /**
     * The digest of the log contents.
     *
     * Generated from protobuf field <code>.google.devtools.remoteexecution.v1test.Digest digest = 1;</code>
     * @return \Google\Devtools\Remoteexecution\V1test\Digest
     */
    public function getDigest()
    {
        return $this->digest;
    }

    /**
     * The digest of the log contents.
     *
     * Generated from protobuf field <code>.google.devtools.remoteexecution.v1test.Digest digest = 1;</code>
     * @param \Google\Devtools\Remoteexecution\V1test\Digest $var
     * @return $this
     */
    public function setDigest($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Remoteexecution\V1test\Digest::class);
        $this->digest = $var;

        return $this;
    }

    /**
     * This is a hint as to the purpose of the log, and is set to true if the log
     * is human-readable text that can be usefully displayed to a user, and false
     * otherwise. For instance, if a command-line client wishes to print the
     * server logs to the terminal for a failed action, this allows it to avoid
     * displaying a binary file.
     *
     * Generated from protobuf field <code>bool human_readable = 2;</code>
     * @return bool
     */
    public function getHumanReadable()
    {
        return $this->human_readable;
    }

    /**
     * This is a hint as to the purpose of the log, and is set to true if the log
     * is human-readable text that can be usefully displayed to a user, and false
     * otherwise. For instance, if a command-line client wishes to print the
     * server logs to the terminal for a failed action, this allows it to avoid
     * displaying a binary file.
     *
     * Generated from protobuf field <code>bool human_readable = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setHumanReadable($var)
    {
        GPBUtil::checkBool($var);
        $this->human_readable = $var;

        return $this;
    }

}

