<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/websecurityscanner/v1alpha/scan_config.proto

namespace Google\Cloud\Websecurityscanner\V1alpha\ScanConfig;

/**
 * Cloud platforms supported by Cloud Web Security Scanner.
 *
 * Protobuf type <code>google.cloud.websecurityscanner.v1alpha.ScanConfig.TargetPlatform</code>
 */
class TargetPlatform
{
    /**
     * The target platform is unknown. Requests with this enum value will be
     * rejected with INVALID_ARGUMENT error.
     *
     * Generated from protobuf enum <code>TARGET_PLATFORM_UNSPECIFIED = 0;</code>
     */
    const TARGET_PLATFORM_UNSPECIFIED = 0;
    /**
     * Google App Engine service.
     *
     * Generated from protobuf enum <code>APP_ENGINE = 1;</code>
     */
    const APP_ENGINE = 1;
    /**
     * Google Compute Engine service.
     *
     * Generated from protobuf enum <code>COMPUTE = 2;</code>
     */
    const COMPUTE = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TargetPlatform::class, \Google\Cloud\Websecurityscanner\V1alpha\ScanConfig_TargetPlatform::class);

