<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/datastore/v1beta3/query.proto

namespace Google\Cloud\Datastore\V1beta3;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Datastore\V1beta3\EntityResult\ResultType instead.
     * @deprecated
     */
    class EntityResult_ResultType {}
}
class_exists(EntityResult\ResultType::class);
@trigger_error('Google\Cloud\Datastore\V1beta3\EntityResult_ResultType is deprecated and will be removed in the next major release. Use Google\Cloud\Datastore\V1beta3\EntityResult\ResultType instead', E_USER_DEPRECATED);

