<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/rpcmessages.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to get a photo.
 * By default
 * - does not return the download URL for the photo bytes.
 * Parameters:
 * - 'view' controls if the download URL for the photo bytes will be returned.
 *
 * Generated from protobuf message <code>google.streetview.publish.v1.GetPhotoRequest</code>
 */
class GetPhotoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. ID of the photo.
     *
     * Generated from protobuf field <code>string photo_id = 1;</code>
     */
    private $photo_id = '';
    /**
     * Specifies if a download URL for the photo bytes should be returned in the
     * Photo response.
     *
     * Generated from protobuf field <code>.google.streetview.publish.v1.PhotoView view = 2;</code>
     */
    private $view = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $photo_id
     *           Required. ID of the photo.
     *     @type int $view
     *           Specifies if a download URL for the photo bytes should be returned in the
     *           Photo response.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Streetview\Publish\V1\Rpcmessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. ID of the photo.
     *
     * Generated from protobuf field <code>string photo_id = 1;</code>
     * @return string
     */
    public function getPhotoId()
    {
        return $this->photo_id;
    }

    /**
     * Required. ID of the photo.
     *
     * Generated from protobuf field <code>string photo_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPhotoId($var)
    {
        GPBUtil::checkString($var, True);
        $this->photo_id = $var;

        return $this;
    }

    /**
     * Specifies if a download URL for the photo bytes should be returned in the
     * Photo response.
     *
     * Generated from protobuf field <code>.google.streetview.publish.v1.PhotoView view = 2;</code>
     * @return int
     */
    public function getView()
    {
        return $this->view;
    }

    /**
     * Specifies if a download URL for the photo bytes should be returned in the
     * Photo response.
     *
     * Generated from protobuf field <code>.google.streetview.publish.v1.PhotoView view = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setView($var)
    {
        GPBUtil::checkEnum($var, \Google\Streetview\Publish\V1\PhotoView::class);
        $this->view = $var;

        return $this;
    }

}

