<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/streetview/publish/v1/resources.proto

namespace Google\Streetview\Publish\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Upload reference for media files.
 *
 * Generated from protobuf message <code>google.streetview.publish.v1.UploadRef</code>
 */
class UploadRef extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. An upload reference should be unique for each user. It follows
     * the form:
     * "https://streetviewpublish.googleapis.com/media/user/<account_id>/photo/<upload_reference>"
     *
     * Generated from protobuf field <code>string upload_url = 1;</code>
     */
    private $upload_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $upload_url
     *           Required. An upload reference should be unique for each user. It follows
     *           the form:
     *           "https://streetviewpublish.googleapis.com/media/user/<account_id>/photo/<upload_reference>"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Streetview\Publish\V1\Resources::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. An upload reference should be unique for each user. It follows
     * the form:
     * "https://streetviewpublish.googleapis.com/media/user/<account_id>/photo/<upload_reference>"
     *
     * Generated from protobuf field <code>string upload_url = 1;</code>
     * @return string
     */
    public function getUploadUrl()
    {
        return $this->upload_url;
    }

    /**
     * Required. An upload reference should be unique for each user. It follows
     * the form:
     * "https://streetviewpublish.googleapis.com/media/user/<account_id>/photo/<upload_reference>"
     *
     * Generated from protobuf field <code>string upload_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUploadUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->upload_url = $var;

        return $this;
    }

}

