<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/remoteworkers/v1test2/bots.proto

namespace Google\Devtools\Remoteworkers\V1test2;

if (false) {
    /**
     * This class is deprecated. Use Google\Devtools\Remoteworkers\V1test2\PostBotEventTempRequest\Type instead.
     * @deprecated
     */
    class PostBotEventTempRequest_Type {}
}
class_exists(PostBotEventTempRequest\Type::class);
@trigger_error('Google\Devtools\Remoteworkers\V1test2\PostBotEventTempRequest_Type is deprecated and will be removed in the next major release. Use Google\Devtools\Remoteworkers\V1test2\PostBotEventTempRequest\Type instead', E_USER_DEPRECATED);

