<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1beta1/deployment/deployment.proto

namespace Grafeas\V1beta1\Deployment;

if (false) {
    /**
     * This class is deprecated. Use Grafeas\V1beta1\Deployment\Deployment\Platform instead.
     * @deprecated
     */
    class Deployment_Platform {}
}
class_exists(Deployment\Platform::class);
@trigger_error('Grafeas\V1beta1\Deployment\Deployment_Platform is deprecated and will be removed in the next major release. Use Grafeas\V1beta1\Deployment\Deployment\Platform instead', E_USER_DEPRECATED);

