<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/endpoint.proto

namespace GPBMetadata\Google\Api;

class Endpoint
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a85020a19676f6f676c652f6170692f656e64706f696e742e70726f746f" .
            "120a676f6f676c652e61706922630a08456e64706f696e74120c0a046e61" .
            "6d6518012001280912130a07616c69617365731802200328094202180112" .
            "100a086665617475726573180420032809120e0a06746172676574186520" .
            "01280912120a0a616c6c6f775f636f7273180520012808426f0a0e636f6d" .
            "2e676f6f676c652e617069420d456e64706f696e7450726f746f50015a45" .
            "676f6f676c652e676f6c616e672e6f72672f67656e70726f746f2f676f6f" .
            "676c65617069732f6170692f73657276696365636f6e6669673b73657276" .
            "696365636f6e666967a2020447415049620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

