<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/firestore/admin/v1beta1/firestore_admin.proto

namespace Google\Firestore\Admin\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Metadata for ExportDocuments operations.
 *
 * Generated from protobuf message <code>google.firestore.admin.v1beta1.ExportDocumentsMetadata</code>
 */
class ExportDocumentsMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * The time that work began on the operation.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 1;</code>
     */
    private $start_time = null;
    /**
     * The time the operation ended, either successfully or otherwise. Unset if
     * the operation is still active.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 2;</code>
     */
    private $end_time = null;
    /**
     * The state of the export operation.
     *
     * Generated from protobuf field <code>.google.firestore.admin.v1beta1.OperationState operation_state = 3;</code>
     */
    private $operation_state = 0;
    /**
     * An estimate of the number of documents processed.
     *
     * Generated from protobuf field <code>.google.firestore.admin.v1beta1.Progress progress_documents = 4;</code>
     */
    private $progress_documents = null;
    /**
     * An estimate of the number of bytes processed.
     *
     * Generated from protobuf field <code>.google.firestore.admin.v1beta1.Progress progress_bytes = 5;</code>
     */
    private $progress_bytes = null;
    /**
     * Which collection ids are being exported.
     *
     * Generated from protobuf field <code>repeated string collection_ids = 6;</code>
     */
    private $collection_ids;
    /**
     * Where the entities are being exported to.
     *
     * Generated from protobuf field <code>string output_uri_prefix = 7;</code>
     */
    private $output_uri_prefix = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $start_time
     *           The time that work began on the operation.
     *     @type \Google\Protobuf\Timestamp $end_time
     *           The time the operation ended, either successfully or otherwise. Unset if
     *           the operation is still active.
     *     @type int $operation_state
     *           The state of the export operation.
     *     @type \Google\Firestore\Admin\V1beta1\Progress $progress_documents
     *           An estimate of the number of documents processed.
     *     @type \Google\Firestore\Admin\V1beta1\Progress $progress_bytes
     *           An estimate of the number of bytes processed.
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $collection_ids
     *           Which collection ids are being exported.
     *     @type string $output_uri_prefix
     *           Where the entities are being exported to.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Firestore\Admin\V1Beta1\FirestoreAdmin::initOnce();
        parent::__construct($data);
    }

    /**
     * The time that work began on the operation.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 1;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * The time that work began on the operation.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_time = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_time = $var;

        return $this;
    }

    /**
     * The time the operation ended, either successfully or otherwise. Unset if
     * the operation is still active.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 2;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * The time the operation ended, either successfully or otherwise. Unset if
     * the operation is still active.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp end_time = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->end_time = $var;

        return $this;
    }

    /**
     * The state of the export operation.
     *
     * Generated from protobuf field <code>.google.firestore.admin.v1beta1.OperationState operation_state = 3;</code>
     * @return int
     */
    public function getOperationState()
    {
        return $this->operation_state;
    }

    /**
     * The state of the export operation.
     *
     * Generated from protobuf field <code>.google.firestore.admin.v1beta1.OperationState operation_state = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOperationState($var)
    {
        GPBUtil::checkEnum($var, \Google\Firestore\Admin\V1beta1\OperationState::class);
        $this->operation_state = $var;

        return $this;
    }

    /**
     * An estimate of the number of documents processed.
     *
     * Generated from protobuf field <code>.google.firestore.admin.v1beta1.Progress progress_documents = 4;</code>
     * @return \Google\Firestore\Admin\V1beta1\Progress
     */
    public function getProgressDocuments()
    {
        return $this->progress_documents;
    }

    /**
     * An estimate of the number of documents processed.
     *
     * Generated from protobuf field <code>.google.firestore.admin.v1beta1.Progress progress_documents = 4;</code>
     * @param \Google\Firestore\Admin\V1beta1\Progress $var
     * @return $this
     */
    public function setProgressDocuments($var)
    {
        GPBUtil::checkMessage($var, \Google\Firestore\Admin\V1beta1\Progress::class);
        $this->progress_documents = $var;

        return $this;
    }

    /**
     * An estimate of the number of bytes processed.
     *
     * Generated from protobuf field <code>.google.firestore.admin.v1beta1.Progress progress_bytes = 5;</code>
     * @return \Google\Firestore\Admin\V1beta1\Progress
     */
    public function getProgressBytes()
    {
        return $this->progress_bytes;
    }

    /**
     * An estimate of the number of bytes processed.
     *
     * Generated from protobuf field <code>.google.firestore.admin.v1beta1.Progress progress_bytes = 5;</code>
     * @param \Google\Firestore\Admin\V1beta1\Progress $var
     * @return $this
     */
    public function setProgressBytes($var)
    {
        GPBUtil::checkMessage($var, \Google\Firestore\Admin\V1beta1\Progress::class);
        $this->progress_bytes = $var;

        return $this;
    }

    /**
     * Which collection ids are being exported.
     *
     * Generated from protobuf field <code>repeated string collection_ids = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCollectionIds()
    {
        return $this->collection_ids;
    }

    /**
     * Which collection ids are being exported.
     *
     * Generated from protobuf field <code>repeated string collection_ids = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCollectionIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->collection_ids = $arr;

        return $this;
    }

    /**
     * Where the entities are being exported to.
     *
     * Generated from protobuf field <code>string output_uri_prefix = 7;</code>
     * @return string
     */
    public function getOutputUriPrefix()
    {
        return $this->output_uri_prefix;
    }

    /**
     * Where the entities are being exported to.
     *
     * Generated from protobuf field <code>string output_uri_prefix = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setOutputUriPrefix($var)
    {
        GPBUtil::checkString($var, True);
        $this->output_uri_prefix = $var;

        return $this;
    }

}

