<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/bigquery/logging/v1/audit_data.proto

namespace Google\Cloud\Bigquery\Logging\V1\JobConfiguration;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes a copy job, which copies an existing table to another table.
 *
 * Generated from protobuf message <code>google.cloud.bigquery.logging.v1.JobConfiguration.TableCopy</code>
 */
class TableCopy extends \Google\Protobuf\Internal\Message
{
    /**
     * Source tables.
     *
     * Generated from protobuf field <code>repeated .google.cloud.bigquery.logging.v1.TableName source_tables = 1;</code>
     */
    private $source_tables;
    /**
     * Destination table.
     *
     * Generated from protobuf field <code>.google.cloud.bigquery.logging.v1.TableName destination_table = 2;</code>
     */
    private $destination_table = null;
    /**
     * Describes when a job is allowed to create a table:
     * `CREATE_IF_NEEDED`, `CREATE_NEVER`.
     *
     * Generated from protobuf field <code>string create_disposition = 3;</code>
     */
    private $create_disposition = '';
    /**
     * Describes how writes affect existing tables:
     * `WRITE_TRUNCATE`, `WRITE_APPEND`, `WRITE_EMPTY`.
     *
     * Generated from protobuf field <code>string write_disposition = 4;</code>
     */
    private $write_disposition = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\Bigquery\Logging\V1\TableName[]|\Google\Protobuf\Internal\RepeatedField $source_tables
     *           Source tables.
     *     @type \Google\Cloud\Bigquery\Logging\V1\TableName $destination_table
     *           Destination table.
     *     @type string $create_disposition
     *           Describes when a job is allowed to create a table:
     *           `CREATE_IF_NEEDED`, `CREATE_NEVER`.
     *     @type string $write_disposition
     *           Describes how writes affect existing tables:
     *           `WRITE_TRUNCATE`, `WRITE_APPEND`, `WRITE_EMPTY`.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Bigquery\Logging\V1\AuditData::initOnce();
        parent::__construct($data);
    }

    /**
     * Source tables.
     *
     * Generated from protobuf field <code>repeated .google.cloud.bigquery.logging.v1.TableName source_tables = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSourceTables()
    {
        return $this->source_tables;
    }

    /**
     * Source tables.
     *
     * Generated from protobuf field <code>repeated .google.cloud.bigquery.logging.v1.TableName source_tables = 1;</code>
     * @param \Google\Cloud\Bigquery\Logging\V1\TableName[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSourceTables($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Bigquery\Logging\V1\TableName::class);
        $this->source_tables = $arr;

        return $this;
    }

    /**
     * Destination table.
     *
     * Generated from protobuf field <code>.google.cloud.bigquery.logging.v1.TableName destination_table = 2;</code>
     * @return \Google\Cloud\Bigquery\Logging\V1\TableName
     */
    public function getDestinationTable()
    {
        return $this->destination_table;
    }

    /**
     * Destination table.
     *
     * Generated from protobuf field <code>.google.cloud.bigquery.logging.v1.TableName destination_table = 2;</code>
     * @param \Google\Cloud\Bigquery\Logging\V1\TableName $var
     * @return $this
     */
    public function setDestinationTable($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Bigquery\Logging\V1\TableName::class);
        $this->destination_table = $var;

        return $this;
    }

    /**
     * Describes when a job is allowed to create a table:
     * `CREATE_IF_NEEDED`, `CREATE_NEVER`.
     *
     * Generated from protobuf field <code>string create_disposition = 3;</code>
     * @return string
     */
    public function getCreateDisposition()
    {
        return $this->create_disposition;
    }

    /**
     * Describes when a job is allowed to create a table:
     * `CREATE_IF_NEEDED`, `CREATE_NEVER`.
     *
     * Generated from protobuf field <code>string create_disposition = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateDisposition($var)
    {
        GPBUtil::checkString($var, True);
        $this->create_disposition = $var;

        return $this;
    }

    /**
     * Describes how writes affect existing tables:
     * `WRITE_TRUNCATE`, `WRITE_APPEND`, `WRITE_EMPTY`.
     *
     * Generated from protobuf field <code>string write_disposition = 4;</code>
     * @return string
     */
    public function getWriteDisposition()
    {
        return $this->write_disposition;
    }

    /**
     * Describes how writes affect existing tables:
     * `WRITE_TRUNCATE`, `WRITE_APPEND`, `WRITE_EMPTY`.
     *
     * Generated from protobuf field <code>string write_disposition = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setWriteDisposition($var)
    {
        GPBUtil::checkString($var, True);
        $this->write_disposition = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TableCopy::class, \Google\Cloud\Bigquery\Logging\V1\JobConfiguration_TableCopy::class);

