<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/support/common.proto

namespace Google\Cloud\Support\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Reference to a Google internal ticket used for investigating a support case.
 * Not every support case will have an internal ticket associated with it.
 * A support case can have multiple tickets linked to it.
 *
 * Generated from protobuf message <code>google.cloud.support.common.CustomerIssue</code>
 */
class CustomerIssue extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique identifier for the internal issue.
     * Output only.
     *
     * Generated from protobuf field <code>string issue_id = 1;</code>
     */
    private $issue_id = '';
    /**
     * Represents current status of the internal ticket.
     * Output only.
     *
     * Generated from protobuf field <code>.google.cloud.support.common.CustomerIssue.IssueState state = 2;</code>
     */
    private $state = 0;
    /**
     * Time when the internal issue was created.
     * Output only.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 3;</code>
     */
    private $create_time = null;
    /**
     * Time when the internal issue was marked as resolved.
     * Output only.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp resolve_time = 4;</code>
     */
    private $resolve_time = null;
    /**
     * Time when the internal issue was last updated.
     * Output only.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp update_time = 5;</code>
     */
    private $update_time = null;

    public function __construct() {
        \GPBMetadata\Google\Cloud\Support\Common::initOnce();
        parent::__construct();
    }

    /**
     * Unique identifier for the internal issue.
     * Output only.
     *
     * Generated from protobuf field <code>string issue_id = 1;</code>
     * @return string
     */
    public function getIssueId()
    {
        return $this->issue_id;
    }

    /**
     * Unique identifier for the internal issue.
     * Output only.
     *
     * Generated from protobuf field <code>string issue_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIssueId($var)
    {
        GPBUtil::checkString($var, True);
        $this->issue_id = $var;

        return $this;
    }

    /**
     * Represents current status of the internal ticket.
     * Output only.
     *
     * Generated from protobuf field <code>.google.cloud.support.common.CustomerIssue.IssueState state = 2;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Represents current status of the internal ticket.
     * Output only.
     *
     * Generated from protobuf field <code>.google.cloud.support.common.CustomerIssue.IssueState state = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\Support\Common\CustomerIssue_IssueState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Time when the internal issue was created.
     * Output only.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 3;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Time when the internal issue was created.
     * Output only.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Time when the internal issue was marked as resolved.
     * Output only.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp resolve_time = 4;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getResolveTime()
    {
        return $this->resolve_time;
    }

    /**
     * Time when the internal issue was marked as resolved.
     * Output only.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp resolve_time = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setResolveTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->resolve_time = $var;

        return $this;
    }

    /**
     * Time when the internal issue was last updated.
     * Output only.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp update_time = 5;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * Time when the internal issue was last updated.
     * Output only.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp update_time = 5;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->update_time = $var;

        return $this;
    }

}

