<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/cloudbuild/v1/cloudbuild.proto

namespace Google\Devtools\Cloudbuild\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Devtools\Cloudbuild\V1\Hash\HashType instead.
     * @deprecated
     */
    class Hash_HashType {}
}
class_exists(Hash\HashType::class);
@trigger_error('Google\Devtools\Cloudbuild\V1\Hash_HashType is deprecated and will be removed in the next major release. Use Google\Devtools\Cloudbuild\V1\Hash\HashType instead', E_USER_DEPRECATED);

