<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/resultstore/v2/configured_target.proto

namespace Google\Devtools\Resultstore\V2;

if (false) {
    /**
     * This class is deprecated. Use Google\Devtools\Resultstore\V2\ConfiguredTarget\Id instead.
     * @deprecated
     */
    class ConfiguredTarget_Id {}
}
class_exists(ConfiguredTarget\Id::class);
@trigger_error('Google\Devtools\Resultstore\V2\ConfiguredTarget_Id is deprecated and will be removed in the next major release. Use Google\Devtools\Resultstore\V2\ConfiguredTarget\Id instead', E_USER_DEPRECATED);

