<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/resultstore/v2/action.proto

namespace Google\Devtools\Resultstore\V2;

/**
 * Errors in file post-processing are categorized using this enum.
 *
 * Protobuf type <code>google.devtools.resultstore.v2.FileProcessingErrorType</code>
 */
class FileProcessingErrorType
{
    /**
     * Type unspecified or not listed here.
     *
     * Generated from protobuf enum <code>FILE_PROCESSING_ERROR_TYPE_UNSPECIFIED = 0;</code>
     */
    const FILE_PROCESSING_ERROR_TYPE_UNSPECIFIED = 0;
    /**
     * A read error occurred trying to read the file.
     *
     * Generated from protobuf enum <code>GENERIC_READ_ERROR = 1;</code>
     */
    const GENERIC_READ_ERROR = 1;
    /**
     * There was an error trying to parse the file.
     *
     * Generated from protobuf enum <code>GENERIC_PARSE_ERROR = 2;</code>
     */
    const GENERIC_PARSE_ERROR = 2;
    /**
     * File is exceeds size limit.
     *
     * Generated from protobuf enum <code>FILE_TOO_LARGE = 3;</code>
     */
    const FILE_TOO_LARGE = 3;
    /**
     * The result of parsing the file exceeded size limit.
     *
     * Generated from protobuf enum <code>OUTPUT_TOO_LARGE = 4;</code>
     */
    const OUTPUT_TOO_LARGE = 4;
    /**
     * Read access to the file was denied by file system.
     *
     * Generated from protobuf enum <code>ACCESS_DENIED = 5;</code>
     */
    const ACCESS_DENIED = 5;
    /**
     * Deadline exceeded trying to read the file.
     *
     * Generated from protobuf enum <code>DEADLINE_EXCEEDED = 6;</code>
     */
    const DEADLINE_EXCEEDED = 6;
    /**
     * File not found.
     *
     * Generated from protobuf enum <code>NOT_FOUND = 7;</code>
     */
    const NOT_FOUND = 7;
}

