<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/resultstore/v2/resultstore_upload.proto

namespace Google\Devtools\Resultstore\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response returned from FinishConfiguredTarget
 *
 * Generated from protobuf message <code>google.devtools.resultstore.v2.FinishConfiguredTargetResponse</code>
 */
class FinishConfiguredTargetResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the configured target. Its format must be:
     * invocations/${INVOCATION_ID}/targets/${TARGET_ID}/configuredTargets/${CONFIG_ID}
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * The resource ID components that identify the ConfiguredTarget.
     *
     * Generated from protobuf field <code>.google.devtools.resultstore.v2.ConfiguredTarget.Id id = 2;</code>
     */
    private $id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the configured target. Its format must be:
     *           invocations/${INVOCATION_ID}/targets/${TARGET_ID}/configuredTargets/${CONFIG_ID}
     *     @type \Google\Devtools\Resultstore\V2\ConfiguredTarget\Id $id
     *           The resource ID components that identify the ConfiguredTarget.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Devtools\Resultstore\V2\ResultstoreUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the configured target. Its format must be:
     * invocations/${INVOCATION_ID}/targets/${TARGET_ID}/configuredTargets/${CONFIG_ID}
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the configured target. Its format must be:
     * invocations/${INVOCATION_ID}/targets/${TARGET_ID}/configuredTargets/${CONFIG_ID}
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The resource ID components that identify the ConfiguredTarget.
     *
     * Generated from protobuf field <code>.google.devtools.resultstore.v2.ConfiguredTarget.Id id = 2;</code>
     * @return \Google\Devtools\Resultstore\V2\ConfiguredTarget\Id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * The resource ID components that identify the ConfiguredTarget.
     *
     * Generated from protobuf field <code>.google.devtools.resultstore.v2.ConfiguredTarget.Id id = 2;</code>
     * @param \Google\Devtools\Resultstore\V2\ConfiguredTarget\Id $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Resultstore\V2\ConfiguredTarget_Id::class);
        $this->id = $var;

        return $this;
    }

}

