<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/resultstore/v2/test_suite.proto

namespace Google\Devtools\Resultstore\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The result of running a test case, as reported in a <testcase> element of
 * an XML log.
 *
 * Generated from protobuf message <code>google.devtools.resultstore.v2.TestCase</code>
 */
class TestCase extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the test case, as reported in the name attribute. For Java,
     * this is normally the method name. Eg. "testBasic".
     *
     * Generated from protobuf field <code>string case_name = 1;</code>
     */
    private $case_name = '';
    /**
     * The name of the class in which the test case was defined, as reported in
     * the classname attribute. For Java, this is normally the fully qualified
     * class name. Eg. "com.google.common.hash.BloomFilterTest".
     *
     * Generated from protobuf field <code>string class_name = 2;</code>
     */
    private $class_name = '';
    /**
     * An enum reported in the result attribute that is used in conjunction with
     * failures and errors below to report the outcome.
     *
     * Generated from protobuf field <code>.google.devtools.resultstore.v2.TestCase.Result result = 3;</code>
     */
    private $result = 0;
    /**
     * Failures reported in <failure> elements within this <testcase>.
     *
     * Generated from protobuf field <code>repeated .google.devtools.resultstore.v2.TestFailure failures = 4;</code>
     */
    private $failures;
    /**
     * Errors reported in <error> elements within this <testcase>.
     *
     * Generated from protobuf field <code>repeated .google.devtools.resultstore.v2.TestError errors = 5;</code>
     */
    private $errors;
    /**
     * The timing for the TestCase, as reported by the time attribute.
     *
     * Generated from protobuf field <code>.google.devtools.resultstore.v2.Timing timing = 7;</code>
     */
    private $timing = null;
    /**
     * Arbitrary name-value pairs, as reported in custom attributes or in a
     * <properties> element within this <testcase>. Multiple properties are
     * allowed with the same key. Properties will be returned in lexicographical
     * order by key.
     *
     * Generated from protobuf field <code>repeated .google.devtools.resultstore.v2.Property properties = 8;</code>
     */
    private $properties;
    /**
     * Files produced by this test case, as reported by undeclared output
     * annotations.
     * The file IDs must be unique within this list. Duplicate file IDs will
     * result in an error. Files will be returned in lexicographical order by ID.
     *
     * Generated from protobuf field <code>repeated .google.devtools.resultstore.v2.File files = 9;</code>
     */
    private $files;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $case_name
     *           The name of the test case, as reported in the name attribute. For Java,
     *           this is normally the method name. Eg. "testBasic".
     *     @type string $class_name
     *           The name of the class in which the test case was defined, as reported in
     *           the classname attribute. For Java, this is normally the fully qualified
     *           class name. Eg. "com.google.common.hash.BloomFilterTest".
     *     @type int $result
     *           An enum reported in the result attribute that is used in conjunction with
     *           failures and errors below to report the outcome.
     *     @type \Google\Devtools\Resultstore\V2\TestFailure[]|\Google\Protobuf\Internal\RepeatedField $failures
     *           Failures reported in <failure> elements within this <testcase>.
     *     @type \Google\Devtools\Resultstore\V2\TestError[]|\Google\Protobuf\Internal\RepeatedField $errors
     *           Errors reported in <error> elements within this <testcase>.
     *     @type \Google\Devtools\Resultstore\V2\Timing $timing
     *           The timing for the TestCase, as reported by the time attribute.
     *     @type \Google\Devtools\Resultstore\V2\Property[]|\Google\Protobuf\Internal\RepeatedField $properties
     *           Arbitrary name-value pairs, as reported in custom attributes or in a
     *           <properties> element within this <testcase>. Multiple properties are
     *           allowed with the same key. Properties will be returned in lexicographical
     *           order by key.
     *     @type \Google\Devtools\Resultstore\V2\File[]|\Google\Protobuf\Internal\RepeatedField $files
     *           Files produced by this test case, as reported by undeclared output
     *           annotations.
     *           The file IDs must be unique within this list. Duplicate file IDs will
     *           result in an error. Files will be returned in lexicographical order by ID.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Devtools\Resultstore\V2\TestSuite::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the test case, as reported in the name attribute. For Java,
     * this is normally the method name. Eg. "testBasic".
     *
     * Generated from protobuf field <code>string case_name = 1;</code>
     * @return string
     */
    public function getCaseName()
    {
        return $this->case_name;
    }

    /**
     * The name of the test case, as reported in the name attribute. For Java,
     * this is normally the method name. Eg. "testBasic".
     *
     * Generated from protobuf field <code>string case_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCaseName($var)
    {
        GPBUtil::checkString($var, True);
        $this->case_name = $var;

        return $this;
    }

    /**
     * The name of the class in which the test case was defined, as reported in
     * the classname attribute. For Java, this is normally the fully qualified
     * class name. Eg. "com.google.common.hash.BloomFilterTest".
     *
     * Generated from protobuf field <code>string class_name = 2;</code>
     * @return string
     */
    public function getClassName()
    {
        return $this->class_name;
    }

    /**
     * The name of the class in which the test case was defined, as reported in
     * the classname attribute. For Java, this is normally the fully qualified
     * class name. Eg. "com.google.common.hash.BloomFilterTest".
     *
     * Generated from protobuf field <code>string class_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClassName($var)
    {
        GPBUtil::checkString($var, True);
        $this->class_name = $var;

        return $this;
    }

    /**
     * An enum reported in the result attribute that is used in conjunction with
     * failures and errors below to report the outcome.
     *
     * Generated from protobuf field <code>.google.devtools.resultstore.v2.TestCase.Result result = 3;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * An enum reported in the result attribute that is used in conjunction with
     * failures and errors below to report the outcome.
     *
     * Generated from protobuf field <code>.google.devtools.resultstore.v2.TestCase.Result result = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Google\Devtools\Resultstore\V2\TestCase_Result::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Failures reported in <failure> elements within this <testcase>.
     *
     * Generated from protobuf field <code>repeated .google.devtools.resultstore.v2.TestFailure failures = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFailures()
    {
        return $this->failures;
    }

    /**
     * Failures reported in <failure> elements within this <testcase>.
     *
     * Generated from protobuf field <code>repeated .google.devtools.resultstore.v2.TestFailure failures = 4;</code>
     * @param \Google\Devtools\Resultstore\V2\TestFailure[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFailures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Devtools\Resultstore\V2\TestFailure::class);
        $this->failures = $arr;

        return $this;
    }

    /**
     * Errors reported in <error> elements within this <testcase>.
     *
     * Generated from protobuf field <code>repeated .google.devtools.resultstore.v2.TestError errors = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Errors reported in <error> elements within this <testcase>.
     *
     * Generated from protobuf field <code>repeated .google.devtools.resultstore.v2.TestError errors = 5;</code>
     * @param \Google\Devtools\Resultstore\V2\TestError[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Devtools\Resultstore\V2\TestError::class);
        $this->errors = $arr;

        return $this;
    }

    /**
     * The timing for the TestCase, as reported by the time attribute.
     *
     * Generated from protobuf field <code>.google.devtools.resultstore.v2.Timing timing = 7;</code>
     * @return \Google\Devtools\Resultstore\V2\Timing
     */
    public function getTiming()
    {
        return $this->timing;
    }

    /**
     * The timing for the TestCase, as reported by the time attribute.
     *
     * Generated from protobuf field <code>.google.devtools.resultstore.v2.Timing timing = 7;</code>
     * @param \Google\Devtools\Resultstore\V2\Timing $var
     * @return $this
     */
    public function setTiming($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Resultstore\V2\Timing::class);
        $this->timing = $var;

        return $this;
    }

    /**
     * Arbitrary name-value pairs, as reported in custom attributes or in a
     * <properties> element within this <testcase>. Multiple properties are
     * allowed with the same key. Properties will be returned in lexicographical
     * order by key.
     *
     * Generated from protobuf field <code>repeated .google.devtools.resultstore.v2.Property properties = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * Arbitrary name-value pairs, as reported in custom attributes or in a
     * <properties> element within this <testcase>. Multiple properties are
     * allowed with the same key. Properties will be returned in lexicographical
     * order by key.
     *
     * Generated from protobuf field <code>repeated .google.devtools.resultstore.v2.Property properties = 8;</code>
     * @param \Google\Devtools\Resultstore\V2\Property[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProperties($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Devtools\Resultstore\V2\Property::class);
        $this->properties = $arr;

        return $this;
    }

    /**
     * Files produced by this test case, as reported by undeclared output
     * annotations.
     * The file IDs must be unique within this list. Duplicate file IDs will
     * result in an error. Files will be returned in lexicographical order by ID.
     *
     * Generated from protobuf field <code>repeated .google.devtools.resultstore.v2.File files = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * Files produced by this test case, as reported by undeclared output
     * annotations.
     * The file IDs must be unique within this list. Duplicate file IDs will
     * result in an error. Files will be returned in lexicographical order by ID.
     *
     * Generated from protobuf field <code>repeated .google.devtools.resultstore.v2.File files = 9;</code>
     * @param \Google\Devtools\Resultstore\V2\File[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFiles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Devtools\Resultstore\V2\File::class);
        $this->files = $arr;

        return $this;
    }

}

