<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/resultstore/v2/resultstore_upload.proto

namespace Google\Devtools\Resultstore\V2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request passed into UpdateFileSet
 *
 * Generated from protobuf message <code>google.devtools.resultstore.v2.UpdateFileSetRequest</code>
 */
class UpdateFileSetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Contains the name and fields of the file set to be updated. The name format
     * must be: invocations/${INVOCATION_ID}/fileSets/${FILE_SET_ID}
     *
     * Generated from protobuf field <code>.google.devtools.resultstore.v2.FileSet file_set = 1;</code>
     */
    private $file_set = null;
    /**
     * Indicates which fields to update.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    private $update_mask = null;
    /**
     * This is a token to authorize access to this invocation. It must be set to
     * the same value that was provided in the CreateInvocationRequest.
     *
     * Generated from protobuf field <code>string authorization_token = 3;</code>
     */
    private $authorization_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Devtools\Resultstore\V2\FileSet $file_set
     *           Contains the name and fields of the file set to be updated. The name format
     *           must be: invocations/${INVOCATION_ID}/fileSets/${FILE_SET_ID}
     *     @type \Google\Protobuf\FieldMask $update_mask
     *           Indicates which fields to update.
     *     @type string $authorization_token
     *           This is a token to authorize access to this invocation. It must be set to
     *           the same value that was provided in the CreateInvocationRequest.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Devtools\Resultstore\V2\ResultstoreUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * Contains the name and fields of the file set to be updated. The name format
     * must be: invocations/${INVOCATION_ID}/fileSets/${FILE_SET_ID}
     *
     * Generated from protobuf field <code>.google.devtools.resultstore.v2.FileSet file_set = 1;</code>
     * @return \Google\Devtools\Resultstore\V2\FileSet
     */
    public function getFileSet()
    {
        return $this->file_set;
    }

    /**
     * Contains the name and fields of the file set to be updated. The name format
     * must be: invocations/${INVOCATION_ID}/fileSets/${FILE_SET_ID}
     *
     * Generated from protobuf field <code>.google.devtools.resultstore.v2.FileSet file_set = 1;</code>
     * @param \Google\Devtools\Resultstore\V2\FileSet $var
     * @return $this
     */
    public function setFileSet($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Resultstore\V2\FileSet::class);
        $this->file_set = $var;

        return $this;
    }

    /**
     * Indicates which fields to update.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @return \Google\Protobuf\FieldMask
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    /**
     * Indicates which fields to update.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setUpdateMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;

        return $this;
    }

    /**
     * This is a token to authorize access to this invocation. It must be set to
     * the same value that was provided in the CreateInvocationRequest.
     *
     * Generated from protobuf field <code>string authorization_token = 3;</code>
     * @return string
     */
    public function getAuthorizationToken()
    {
        return $this->authorization_token;
    }

    /**
     * This is a token to authorize access to this invocation. It must be set to
     * the same value that was provided in the CreateInvocationRequest.
     *
     * Generated from protobuf field <code>string authorization_token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthorizationToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->authorization_token = $var;

        return $this;
    }

}

