<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1beta1/package/package.proto

namespace Grafeas\V1beta1\Package;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Details of a package occurrence.
 *
 * Generated from protobuf message <code>grafeas.v1beta1.package.Details</code>
 */
class Details extends \Google\Protobuf\Internal\Message
{
    /**
     * Where the package was installed.
     *
     * Generated from protobuf field <code>.grafeas.v1beta1.package.Installation installation = 1;</code>
     */
    private $installation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Grafeas\V1beta1\Package\Installation $installation
     *           Where the package was installed.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Devtools\Containeranalysis\V1Beta1\Package\Package::initOnce();
        parent::__construct($data);
    }

    /**
     * Where the package was installed.
     *
     * Generated from protobuf field <code>.grafeas.v1beta1.package.Installation installation = 1;</code>
     * @return \Grafeas\V1beta1\Package\Installation
     */
    public function getInstallation()
    {
        return $this->installation;
    }

    /**
     * Where the package was installed.
     *
     * Generated from protobuf field <code>.grafeas.v1beta1.package.Installation installation = 1;</code>
     * @param \Grafeas\V1beta1\Package\Installation $var
     * @return $this
     */
    public function setInstallation($var)
    {
        GPBUtil::checkMessage($var, \Grafeas\V1beta1\Package\Installation::class);
        $this->installation = $var;

        return $this;
    }

}

