<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/datastore/v1/datastore.proto

namespace Google\Cloud\Datastore\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response for [Datastore.ReserveIds][google.datastore.v1.Datastore.ReserveIds].
 *
 * Generated from protobuf message <code>google.datastore.v1.ReserveIdsResponse</code>
 */
class ReserveIdsResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Google\Datastore\V1\Datastore::initOnce();
        parent::__construct();
    }

}

