<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/variants.proto

namespace Google\Genomics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.genomics.v1.UpdateVariantSetRequest</code>
 */
class UpdateVariantSetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The ID of the variant to be updated (must already exist).
     *
     * Generated from protobuf field <code>string variant_set_id = 1;</code>
     */
    private $variant_set_id = '';
    /**
     * The new variant data. Only the variant_set.metadata will be considered
     * for update.
     *
     * Generated from protobuf field <code>.google.genomics.v1.VariantSet variant_set = 2;</code>
     */
    private $variant_set = null;
    /**
     * An optional mask specifying which fields to update. Supported fields:
     * * [metadata][google.genomics.v1.VariantSet.metadata].
     * * [name][google.genomics.v1.VariantSet.name].
     * * [description][google.genomics.v1.VariantSet.description].
     * Leaving `updateMask` unset is equivalent to specifying all mutable
     * fields.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 5;</code>
     */
    private $update_mask = null;

    public function __construct() {
        \GPBMetadata\Google\Genomics\V1\Variants::initOnce();
        parent::__construct();
    }

    /**
     * The ID of the variant to be updated (must already exist).
     *
     * Generated from protobuf field <code>string variant_set_id = 1;</code>
     * @return string
     */
    public function getVariantSetId()
    {
        return $this->variant_set_id;
    }

    /**
     * The ID of the variant to be updated (must already exist).
     *
     * Generated from protobuf field <code>string variant_set_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVariantSetId($var)
    {
        GPBUtil::checkString($var, True);
        $this->variant_set_id = $var;

        return $this;
    }

    /**
     * The new variant data. Only the variant_set.metadata will be considered
     * for update.
     *
     * Generated from protobuf field <code>.google.genomics.v1.VariantSet variant_set = 2;</code>
     * @return \Google\Genomics\V1\VariantSet
     */
    public function getVariantSet()
    {
        return $this->variant_set;
    }

    /**
     * The new variant data. Only the variant_set.metadata will be considered
     * for update.
     *
     * Generated from protobuf field <code>.google.genomics.v1.VariantSet variant_set = 2;</code>
     * @param \Google\Genomics\V1\VariantSet $var
     * @return $this
     */
    public function setVariantSet($var)
    {
        GPBUtil::checkMessage($var, \Google\Genomics\V1\VariantSet::class);
        $this->variant_set = $var;

        return $this;
    }

    /**
     * An optional mask specifying which fields to update. Supported fields:
     * * [metadata][google.genomics.v1.VariantSet.metadata].
     * * [name][google.genomics.v1.VariantSet.name].
     * * [description][google.genomics.v1.VariantSet.description].
     * Leaving `updateMask` unset is equivalent to specifying all mutable
     * fields.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 5;</code>
     * @return \Google\Protobuf\FieldMask
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    /**
     * An optional mask specifying which fields to update. Supported fields:
     * * [metadata][google.genomics.v1.VariantSet.metadata].
     * * [name][google.genomics.v1.VariantSet.name].
     * * [description][google.genomics.v1.VariantSet.description].
     * Leaving `updateMask` unset is equivalent to specifying all mutable
     * fields.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 5;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setUpdateMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;

        return $this;
    }

}

