<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/ml/v1beta1/job_service.proto

namespace Google\Cloud\Ml\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request message for the CreateJob method.
 *
 * Generated from protobuf message <code>google.cloud.ml.v1beta1.CreateJobRequest</code>
 */
class CreateJobRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The project name.
     * Authorization: requires `Editor` role on the specified project.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     */
    private $parent = '';
    /**
     * Required. The job to create.
     *
     * Generated from protobuf field <code>.google.cloud.ml.v1beta1.Job job = 2;</code>
     */
    private $job = null;

    public function __construct() {
        \GPBMetadata\Google\Cloud\Ml\V1Beta1\JobService::initOnce();
        parent::__construct();
    }

    /**
     * Required. The project name.
     * Authorization: requires `Editor` role on the specified project.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The project name.
     * Authorization: requires `Editor` role on the specified project.
     *
     * Generated from protobuf field <code>string parent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Required. The job to create.
     *
     * Generated from protobuf field <code>.google.cloud.ml.v1beta1.Job job = 2;</code>
     * @return \Google\Cloud\Ml\V1beta1\Job
     */
    public function getJob()
    {
        return $this->job;
    }

    /**
     * Required. The job to create.
     *
     * Generated from protobuf field <code>.google.cloud.ml.v1beta1.Job job = 2;</code>
     * @param \Google\Cloud\Ml\V1beta1\Job $var
     * @return $this
     */
    public function setJob($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Ml\V1beta1\Job::class);
        $this->job = $var;

        return $this;
    }

}

