<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v0/common/criteria.proto

namespace Google\Ads\GoogleAds\V0\Common;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Criterion for day of the week the booking is for.
 *
 * Generated from protobuf message <code>google.ads.googleads.v0.common.HotelCheckInDayInfo</code>
 */
class HotelCheckInDayInfo extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Google\Ads\GoogleAds\V0\Common\Criteria::initOnce();
        parent::__construct($data);
    }

}

