<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1alpha1/containeranalysis.proto

namespace Google\Devtools\Containeranalysis\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Note holding the version of the provider's builder and the signature of
 * the provenance message in linked BuildDetails.
 *
 * Generated from protobuf message <code>google.devtools.containeranalysis.v1alpha1.BuildType</code>
 */
class BuildType extends \Google\Protobuf\Internal\Message
{
    /**
     * Version of the builder which produced this Note.
     *
     * Generated from protobuf field <code>string builder_version = 1;</code>
     */
    private $builder_version = '';
    /**
     * Signature of the build in Occurrences pointing to the Note containing this
     * `BuilderDetails`.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.BuildSignature signature = 2;</code>
     */
    private $signature = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $builder_version
     *           Version of the builder which produced this Note.
     *     @type \Google\Devtools\Containeranalysis\V1alpha1\BuildSignature $signature
     *           Signature of the build in Occurrences pointing to the Note containing this
     *           `BuilderDetails`.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Devtools\Containeranalysis\V1Alpha1\Containeranalysis::initOnce();
        parent::__construct($data);
    }

    /**
     * Version of the builder which produced this Note.
     *
     * Generated from protobuf field <code>string builder_version = 1;</code>
     * @return string
     */
    public function getBuilderVersion()
    {
        return $this->builder_version;
    }

    /**
     * Version of the builder which produced this Note.
     *
     * Generated from protobuf field <code>string builder_version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBuilderVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->builder_version = $var;

        return $this;
    }

    /**
     * Signature of the build in Occurrences pointing to the Note containing this
     * `BuilderDetails`.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.BuildSignature signature = 2;</code>
     * @return \Google\Devtools\Containeranalysis\V1alpha1\BuildSignature
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Signature of the build in Occurrences pointing to the Note containing this
     * `BuilderDetails`.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.BuildSignature signature = 2;</code>
     * @param \Google\Devtools\Containeranalysis\V1alpha1\BuildSignature $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Containeranalysis\V1alpha1\BuildSignature::class);
        $this->signature = $var;

        return $this;
    }

}

