<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1alpha1/containeranalysis.proto

namespace Google\Devtools\Containeranalysis\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request to get a ScanConfig.
 *
 * Generated from protobuf message <code>google.devtools.containeranalysis.v1alpha1.GetScanConfigRequest</code>
 */
class GetScanConfigRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the ScanConfig in the form
     * projects/{project_id}/scan_configs/{ScanConfig_id}
     * instead.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the ScanConfig in the form
     *           projects/{project_id}/scan_configs/{ScanConfig_id}
     *           instead.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Devtools\Containeranalysis\V1Alpha1\Containeranalysis::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the ScanConfig in the form
     * projects/{project_id}/scan_configs/{ScanConfig_id}
     * instead.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the ScanConfig in the form
     * projects/{project_id}/scan_configs/{ScanConfig_id}
     * instead.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

