<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1alpha1/containeranalysis.proto

namespace Google\Devtools\Containeranalysis\V1alpha1;

if (false) {
    /**
     * This class is deprecated. Use Google\Devtools\Containeranalysis\V1alpha1\Note\RelatedUrl instead.
     * @deprecated
     */
    class Note_RelatedUrl {}
}
class_exists(Note\RelatedUrl::class);
@trigger_error('Google\Devtools\Containeranalysis\V1alpha1\Note_RelatedUrl is deprecated and will be removed in the next major release. Use Google\Devtools\Containeranalysis\V1alpha1\Note\RelatedUrl instead', E_USER_DEPRECATED);

