<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/containeranalysis/v1alpha1/containeranalysis.proto

namespace Google\Devtools\Containeranalysis\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * `Occurrence` includes information about analysis occurrences for an image.
 *
 * Generated from protobuf message <code>google.devtools.containeranalysis.v1alpha1.Occurrence</code>
 */
class Occurrence extends \Google\Protobuf\Internal\Message
{
    /**
     * Output only. The name of the `Occurrence` in the form
     * "projects/{project_id}/occurrences/{OCCURRENCE_ID}"
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * The unique URL of the image or the container for which the `Occurrence`
     * applies. For example, https://gcr.io/project/image&#64;sha256:foo This field
     * can be used as a filter in list requests.
     *
     * Generated from protobuf field <code>string resource_url = 2;</code>
     */
    private $resource_url = '';
    /**
     * The resource for which the `Occurrence` applies.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.Resource resource = 17;</code>
     */
    private $resource = null;
    /**
     * An analysis note associated with this image, in the form
     * "providers/{provider_id}/notes/{NOTE_ID}"
     * This field can be used as a filter in list requests.
     *
     * Generated from protobuf field <code>string note_name = 3;</code>
     */
    private $note_name = '';
    /**
     * Output only. This explicitly denotes which of the `Occurrence` details are
     * specified. This field can be used as a filter in list requests.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.Note.Kind kind = 6;</code>
     */
    private $kind = 0;
    /**
     * A description of actions that can be taken to remedy the `Note`
     *
     * Generated from protobuf field <code>string remediation = 5;</code>
     */
    private $remediation = '';
    /**
     * Output only. The time this `Occurrence` was created.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 9;</code>
     */
    private $create_time = null;
    /**
     * Output only. The time this `Occurrence` was last updated.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp update_time = 10;</code>
     */
    private $update_time = null;
    protected $details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Output only. The name of the `Occurrence` in the form
     *           "projects/{project_id}/occurrences/{OCCURRENCE_ID}"
     *     @type string $resource_url
     *           The unique URL of the image or the container for which the `Occurrence`
     *           applies. For example, https://gcr.io/project/image&#64;sha256:foo This field
     *           can be used as a filter in list requests.
     *     @type \Google\Devtools\Containeranalysis\V1alpha1\Resource $resource
     *           The resource for which the `Occurrence` applies.
     *     @type string $note_name
     *           An analysis note associated with this image, in the form
     *           "providers/{provider_id}/notes/{NOTE_ID}"
     *           This field can be used as a filter in list requests.
     *     @type int $kind
     *           Output only. This explicitly denotes which of the `Occurrence` details are
     *           specified. This field can be used as a filter in list requests.
     *     @type \Google\Devtools\Containeranalysis\V1alpha1\VulnerabilityType\VulnerabilityDetails $vulnerability_details
     *           Details of a security vulnerability note.
     *     @type \Google\Devtools\Containeranalysis\V1alpha1\BuildDetails $build_details
     *           Build details for a verifiable build.
     *     @type \Google\Devtools\Containeranalysis\V1alpha1\DockerImage\Derived $derived_image
     *           Describes how this resource derives from the basis
     *           in the associated note.
     *     @type \Google\Devtools\Containeranalysis\V1alpha1\PackageManager\Installation $installation
     *           Describes the installation of a package on the linked resource.
     *     @type \Google\Devtools\Containeranalysis\V1alpha1\Deployable\Deployment $deployment
     *           Describes the deployment of an artifact on a runtime.
     *     @type \Google\Devtools\Containeranalysis\V1alpha1\Discovery\Discovered $discovered
     *           Describes the initial scan status for this resource.
     *     @type \Google\Devtools\Containeranalysis\V1alpha1\AttestationAuthority\Attestation $attestation
     *           Describes an attestation of an artifact.
     *     @type string $remediation
     *           A description of actions that can be taken to remedy the `Note`
     *     @type \Google\Protobuf\Timestamp $create_time
     *           Output only. The time this `Occurrence` was created.
     *     @type \Google\Protobuf\Timestamp $update_time
     *           Output only. The time this `Occurrence` was last updated.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Devtools\Containeranalysis\V1Alpha1\Containeranalysis::initOnce();
        parent::__construct($data);
    }

    /**
     * Output only. The name of the `Occurrence` in the form
     * "projects/{project_id}/occurrences/{OCCURRENCE_ID}"
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Output only. The name of the `Occurrence` in the form
     * "projects/{project_id}/occurrences/{OCCURRENCE_ID}"
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The unique URL of the image or the container for which the `Occurrence`
     * applies. For example, https://gcr.io/project/image&#64;sha256:foo This field
     * can be used as a filter in list requests.
     *
     * Generated from protobuf field <code>string resource_url = 2;</code>
     * @return string
     */
    public function getResourceUrl()
    {
        return $this->resource_url;
    }

    /**
     * The unique URL of the image or the container for which the `Occurrence`
     * applies. For example, https://gcr.io/project/image&#64;sha256:foo This field
     * can be used as a filter in list requests.
     *
     * Generated from protobuf field <code>string resource_url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setResourceUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_url = $var;

        return $this;
    }

    /**
     * The resource for which the `Occurrence` applies.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.Resource resource = 17;</code>
     * @return \Google\Devtools\Containeranalysis\V1alpha1\Resource
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * The resource for which the `Occurrence` applies.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.Resource resource = 17;</code>
     * @param \Google\Devtools\Containeranalysis\V1alpha1\Resource $var
     * @return $this
     */
    public function setResource($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Containeranalysis\V1alpha1\Resource::class);
        $this->resource = $var;

        return $this;
    }

    /**
     * An analysis note associated with this image, in the form
     * "providers/{provider_id}/notes/{NOTE_ID}"
     * This field can be used as a filter in list requests.
     *
     * Generated from protobuf field <code>string note_name = 3;</code>
     * @return string
     */
    public function getNoteName()
    {
        return $this->note_name;
    }

    /**
     * An analysis note associated with this image, in the form
     * "providers/{provider_id}/notes/{NOTE_ID}"
     * This field can be used as a filter in list requests.
     *
     * Generated from protobuf field <code>string note_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNoteName($var)
    {
        GPBUtil::checkString($var, True);
        $this->note_name = $var;

        return $this;
    }

    /**
     * Output only. This explicitly denotes which of the `Occurrence` details are
     * specified. This field can be used as a filter in list requests.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.Note.Kind kind = 6;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Output only. This explicitly denotes which of the `Occurrence` details are
     * specified. This field can be used as a filter in list requests.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.Note.Kind kind = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Google\Devtools\Containeranalysis\V1alpha1\Note_Kind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     * Details of a security vulnerability note.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.VulnerabilityType.VulnerabilityDetails vulnerability_details = 8;</code>
     * @return \Google\Devtools\Containeranalysis\V1alpha1\VulnerabilityType\VulnerabilityDetails
     */
    public function getVulnerabilityDetails()
    {
        return $this->readOneof(8);
    }

    /**
     * Details of a security vulnerability note.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.VulnerabilityType.VulnerabilityDetails vulnerability_details = 8;</code>
     * @param \Google\Devtools\Containeranalysis\V1alpha1\VulnerabilityType\VulnerabilityDetails $var
     * @return $this
     */
    public function setVulnerabilityDetails($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Containeranalysis\V1alpha1\VulnerabilityType_VulnerabilityDetails::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Build details for a verifiable build.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.BuildDetails build_details = 7;</code>
     * @return \Google\Devtools\Containeranalysis\V1alpha1\BuildDetails
     */
    public function getBuildDetails()
    {
        return $this->readOneof(7);
    }

    /**
     * Build details for a verifiable build.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.BuildDetails build_details = 7;</code>
     * @param \Google\Devtools\Containeranalysis\V1alpha1\BuildDetails $var
     * @return $this
     */
    public function setBuildDetails($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Containeranalysis\V1alpha1\BuildDetails::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Describes how this resource derives from the basis
     * in the associated note.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.DockerImage.Derived derived_image = 11;</code>
     * @return \Google\Devtools\Containeranalysis\V1alpha1\DockerImage\Derived
     */
    public function getDerivedImage()
    {
        return $this->readOneof(11);
    }

    /**
     * Describes how this resource derives from the basis
     * in the associated note.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.DockerImage.Derived derived_image = 11;</code>
     * @param \Google\Devtools\Containeranalysis\V1alpha1\DockerImage\Derived $var
     * @return $this
     */
    public function setDerivedImage($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Containeranalysis\V1alpha1\DockerImage_Derived::class);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Describes the installation of a package on the linked resource.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation installation = 12;</code>
     * @return \Google\Devtools\Containeranalysis\V1alpha1\PackageManager\Installation
     */
    public function getInstallation()
    {
        return $this->readOneof(12);
    }

    /**
     * Describes the installation of a package on the linked resource.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.PackageManager.Installation installation = 12;</code>
     * @param \Google\Devtools\Containeranalysis\V1alpha1\PackageManager\Installation $var
     * @return $this
     */
    public function setInstallation($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Containeranalysis\V1alpha1\PackageManager_Installation::class);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Describes the deployment of an artifact on a runtime.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.Deployable.Deployment deployment = 14;</code>
     * @return \Google\Devtools\Containeranalysis\V1alpha1\Deployable\Deployment
     */
    public function getDeployment()
    {
        return $this->readOneof(14);
    }

    /**
     * Describes the deployment of an artifact on a runtime.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.Deployable.Deployment deployment = 14;</code>
     * @param \Google\Devtools\Containeranalysis\V1alpha1\Deployable\Deployment $var
     * @return $this
     */
    public function setDeployment($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Containeranalysis\V1alpha1\Deployable_Deployment::class);
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * Describes the initial scan status for this resource.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.Discovery.Discovered discovered = 15;</code>
     * @return \Google\Devtools\Containeranalysis\V1alpha1\Discovery\Discovered
     */
    public function getDiscovered()
    {
        return $this->readOneof(15);
    }

    /**
     * Describes the initial scan status for this resource.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.Discovery.Discovered discovered = 15;</code>
     * @param \Google\Devtools\Containeranalysis\V1alpha1\Discovery\Discovered $var
     * @return $this
     */
    public function setDiscovered($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Containeranalysis\V1alpha1\Discovery_Discovered::class);
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * Describes an attestation of an artifact.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.AttestationAuthority.Attestation attestation = 16;</code>
     * @return \Google\Devtools\Containeranalysis\V1alpha1\AttestationAuthority\Attestation
     */
    public function getAttestation()
    {
        return $this->readOneof(16);
    }

    /**
     * Describes an attestation of an artifact.
     *
     * Generated from protobuf field <code>.google.devtools.containeranalysis.v1alpha1.AttestationAuthority.Attestation attestation = 16;</code>
     * @param \Google\Devtools\Containeranalysis\V1alpha1\AttestationAuthority\Attestation $var
     * @return $this
     */
    public function setAttestation($var)
    {
        GPBUtil::checkMessage($var, \Google\Devtools\Containeranalysis\V1alpha1\AttestationAuthority_Attestation::class);
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     * A description of actions that can be taken to remedy the `Note`
     *
     * Generated from protobuf field <code>string remediation = 5;</code>
     * @return string
     */
    public function getRemediation()
    {
        return $this->remediation;
    }

    /**
     * A description of actions that can be taken to remedy the `Note`
     *
     * Generated from protobuf field <code>string remediation = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRemediation($var)
    {
        GPBUtil::checkString($var, True);
        $this->remediation = $var;

        return $this;
    }

    /**
     * Output only. The time this `Occurrence` was created.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 9;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Output only. The time this `Occurrence` was created.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp create_time = 9;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->create_time = $var;

        return $this;
    }

    /**
     * Output only. The time this `Occurrence` was last updated.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp update_time = 10;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * Output only. The time this `Occurrence` was last updated.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp update_time = 10;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdateTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->update_time = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getDetails()
    {
        return $this->whichOneof("details");
    }

}

