<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/genomics/v1/cigar.proto

namespace GPBMetadata\Google\Genomics\V1;

class Cigar
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad5030a1e676f6f676c652f67656e6f6d6963732f76312f63696761722e" .
            "70726f746f1212676f6f676c652e67656e6f6d6963732e763122af020a09" .
            "4369676172556e6974123a0a096f7065726174696f6e18012001280e3227" .
            "2e676f6f676c652e67656e6f6d6963732e76312e4369676172556e69742e" .
            "4f7065726174696f6e12180a106f7065726174696f6e5f6c656e67746818" .
            "0220012803121a0a127265666572656e63655f73657175656e6365180320" .
            "01280922af010a094f7065726174696f6e12190a154f5045524154494f4e" .
            "5f554e535045434946494544100012130a0f414c49474e4d454e545f4d41" .
            "5443481001120a0a06494e534552541002120a0a0644454c455445100312" .
            "080a04534b49501004120d0a09434c49505f534f46541005120d0a09434c" .
            "49505f48415244100612070a03504144100712120a0e53455155454e4345" .
            "5f4d41544348100812150a1153455155454e43455f4d49534d4154434810" .
            "0942650a16636f6d2e676f6f676c652e67656e6f6d6963732e7631420a43" .
            "6967617250726f746f50015a3a676f6f676c652e676f6c616e672e6f7267" .
            "2f67656e70726f746f2f676f6f676c65617069732f67656e6f6d6963732f" .
            "76313b67656e6f6d696373f80101620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

