<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/bigquery/storage/v1beta1/avro.proto

namespace GPBMetadata\Google\Cloud\Bigquery\Storage\V1Beta1;

class Avro
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5020a30676f6f676c652f636c6f75642f62696771756572792f73746f" .
            "726167652f763162657461312f6176726f2e70726f746f1225676f6f676c" .
            "652e636c6f75642e62696771756572792e73746f726167652e7631626574" .
            "6131221c0a0a4176726f536368656d61120e0a06736368656d6118012001" .
            "2809223d0a084176726f526f7773121e0a1673657269616c697a65645f62" .
            "696e6172795f726f777318012001280c12110a09726f775f636f756e7418" .
            "02200128034284010a29636f6d2e676f6f676c652e636c6f75642e626967" .
            "71756572792e73746f726167652e7631626574613142094176726f50726f" .
            "746f5a4c676f6f676c652e676f6c616e672e6f72672f67656e70726f746f" .
            "2f676f6f676c65617069732f636c6f75642f62696771756572792f73746f" .
            "726167652f763162657461313b73746f72616765620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

