<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/assistant/embedded/v1alpha2/embedded_assistant.proto

namespace Google\Assistant\Embedded\V1alpha2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Provides information about the current dialog state.
 *
 * Generated from protobuf message <code>google.assistant.embedded.v1alpha2.DialogStateIn</code>
 */
class DialogStateIn extends \Google\Protobuf\Internal\Message
{
    /**
     * *Required* This field must always be set to the
     * [DialogStateOut.conversation_state][google.assistant.embedded.v1alpha2.DialogStateOut.conversation_state] value that was returned in the prior
     * `Assist` RPC. It should only be omitted (field not set) if there was no
     * prior `Assist` RPC because this is the first `Assist` RPC made by this
     * device after it was first setup and/or a factory-default reset.
     *
     * Generated from protobuf field <code>bytes conversation_state = 1;</code>
     */
    private $conversation_state = '';
    /**
     * *Required* Language of the request in
     * [IETF BCP 47 syntax](https://tools.ietf.org/html/bcp47) (for example,
     * "en-US"). See [Language Support](https://developers.google.com/assistant/sdk/reference/rpc/languages)
     * for more information. If you have selected a language for this `device_id`
     * using the [Settings](https://developers.google.com/assistant/sdk/reference/assistant-app/assistant-settings)
     * menu in your phone's Google Assistant app, that selection will override
     * this value.
     *
     * Generated from protobuf field <code>string language_code = 2;</code>
     */
    private $language_code = '';
    /**
     * *Optional* Location of the device where the query originated.
     *
     * Generated from protobuf field <code>.google.assistant.embedded.v1alpha2.DeviceLocation device_location = 5;</code>
     */
    private $device_location = null;
    /**
     * *Optional* If true, the server will treat the request as a new conversation
     * and not use state from the prior request. Set this field to true when the
     * conversation should be restarted, such as after a device reboot, or after a
     * significant lapse of time since the prior query.
     *
     * Generated from protobuf field <code>bool is_new_conversation = 7;</code>
     */
    private $is_new_conversation = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $conversation_state
     *           *Required* This field must always be set to the
     *           [DialogStateOut.conversation_state][google.assistant.embedded.v1alpha2.DialogStateOut.conversation_state] value that was returned in the prior
     *           `Assist` RPC. It should only be omitted (field not set) if there was no
     *           prior `Assist` RPC because this is the first `Assist` RPC made by this
     *           device after it was first setup and/or a factory-default reset.
     *     @type string $language_code
     *           *Required* Language of the request in
     *           [IETF BCP 47 syntax](https://tools.ietf.org/html/bcp47) (for example,
     *           "en-US"). See [Language Support](https://developers.google.com/assistant/sdk/reference/rpc/languages)
     *           for more information. If you have selected a language for this `device_id`
     *           using the [Settings](https://developers.google.com/assistant/sdk/reference/assistant-app/assistant-settings)
     *           menu in your phone's Google Assistant app, that selection will override
     *           this value.
     *     @type \Google\Assistant\Embedded\V1alpha2\DeviceLocation $device_location
     *           *Optional* Location of the device where the query originated.
     *     @type bool $is_new_conversation
     *           *Optional* If true, the server will treat the request as a new conversation
     *           and not use state from the prior request. Set this field to true when the
     *           conversation should be restarted, such as after a device reboot, or after a
     *           significant lapse of time since the prior query.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Assistant\Embedded\V1Alpha2\EmbeddedAssistant::initOnce();
        parent::__construct($data);
    }

    /**
     * *Required* This field must always be set to the
     * [DialogStateOut.conversation_state][google.assistant.embedded.v1alpha2.DialogStateOut.conversation_state] value that was returned in the prior
     * `Assist` RPC. It should only be omitted (field not set) if there was no
     * prior `Assist` RPC because this is the first `Assist` RPC made by this
     * device after it was first setup and/or a factory-default reset.
     *
     * Generated from protobuf field <code>bytes conversation_state = 1;</code>
     * @return string
     */
    public function getConversationState()
    {
        return $this->conversation_state;
    }

    /**
     * *Required* This field must always be set to the
     * [DialogStateOut.conversation_state][google.assistant.embedded.v1alpha2.DialogStateOut.conversation_state] value that was returned in the prior
     * `Assist` RPC. It should only be omitted (field not set) if there was no
     * prior `Assist` RPC because this is the first `Assist` RPC made by this
     * device after it was first setup and/or a factory-default reset.
     *
     * Generated from protobuf field <code>bytes conversation_state = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConversationState($var)
    {
        GPBUtil::checkString($var, False);
        $this->conversation_state = $var;

        return $this;
    }

    /**
     * *Required* Language of the request in
     * [IETF BCP 47 syntax](https://tools.ietf.org/html/bcp47) (for example,
     * "en-US"). See [Language Support](https://developers.google.com/assistant/sdk/reference/rpc/languages)
     * for more information. If you have selected a language for this `device_id`
     * using the [Settings](https://developers.google.com/assistant/sdk/reference/assistant-app/assistant-settings)
     * menu in your phone's Google Assistant app, that selection will override
     * this value.
     *
     * Generated from protobuf field <code>string language_code = 2;</code>
     * @return string
     */
    public function getLanguageCode()
    {
        return $this->language_code;
    }

    /**
     * *Required* Language of the request in
     * [IETF BCP 47 syntax](https://tools.ietf.org/html/bcp47) (for example,
     * "en-US"). See [Language Support](https://developers.google.com/assistant/sdk/reference/rpc/languages)
     * for more information. If you have selected a language for this `device_id`
     * using the [Settings](https://developers.google.com/assistant/sdk/reference/assistant-app/assistant-settings)
     * menu in your phone's Google Assistant app, that selection will override
     * this value.
     *
     * Generated from protobuf field <code>string language_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguageCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->language_code = $var;

        return $this;
    }

    /**
     * *Optional* Location of the device where the query originated.
     *
     * Generated from protobuf field <code>.google.assistant.embedded.v1alpha2.DeviceLocation device_location = 5;</code>
     * @return \Google\Assistant\Embedded\V1alpha2\DeviceLocation
     */
    public function getDeviceLocation()
    {
        return $this->device_location;
    }

    /**
     * *Optional* Location of the device where the query originated.
     *
     * Generated from protobuf field <code>.google.assistant.embedded.v1alpha2.DeviceLocation device_location = 5;</code>
     * @param \Google\Assistant\Embedded\V1alpha2\DeviceLocation $var
     * @return $this
     */
    public function setDeviceLocation($var)
    {
        GPBUtil::checkMessage($var, \Google\Assistant\Embedded\V1alpha2\DeviceLocation::class);
        $this->device_location = $var;

        return $this;
    }

    /**
     * *Optional* If true, the server will treat the request as a new conversation
     * and not use state from the prior request. Set this field to true when the
     * conversation should be restarted, such as after a device reboot, or after a
     * significant lapse of time since the prior query.
     *
     * Generated from protobuf field <code>bool is_new_conversation = 7;</code>
     * @return bool
     */
    public function getIsNewConversation()
    {
        return $this->is_new_conversation;
    }

    /**
     * *Optional* If true, the server will treat the request as a new conversation
     * and not use state from the prior request. Set this field to true when the
     * conversation should be restarted, such as after a device reboot, or after a
     * significant lapse of time since the prior query.
     *
     * Generated from protobuf field <code>bool is_new_conversation = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsNewConversation($var)
    {
        GPBUtil::checkBool($var);
        $this->is_new_conversation = $var;

        return $this;
    }

}

