<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/assistant/embedded/v1alpha2/embedded_assistant.proto

namespace Google\Assistant\Embedded\V1alpha2;

if (false) {
    /**
     * This class is deprecated. Use Google\Assistant\Embedded\V1alpha2\DialogStateOut\MicrophoneMode instead.
     * @deprecated
     */
    class DialogStateOut_MicrophoneMode {}
}
class_exists(DialogStateOut\MicrophoneMode::class);
@trigger_error('Google\Assistant\Embedded\V1alpha2\DialogStateOut_MicrophoneMode is deprecated and will be removed in the next major release. Use Google\Assistant\Embedded\V1alpha2\DialogStateOut\MicrophoneMode instead', E_USER_DEPRECATED);

